### ISSUE TITLE
Symbol not found: __ZNK2at6Tensor8data_ptrIlEEPT_v

### ISSUE THREAD

**Issue by iliesaya** [NVIDIA/MinkowskiEngine#106]
I am trying to rin MinkowskiEngine from Conda , I followed the instructions, here are some command I ran :

```
`
conda install numpy mkl-include
conda install pytorch -c pytorch
pip install open3d
conda install -c anaconda clang
conda install -c anaconda openblas
conda install pytorch torchvision -c pytorch
conda install openblas numpy
python setup.py install --force
conda install cudatoolkit 
make clean
conda install pytorch torchvision cudatoolkit=9.0 -c pytorch 


python -m examples.reconstruction --trainpython -m examples.reconstruction --train
`
```

here is the result :

`
Traceback (most recent call last):
  File "/Users/aya/opt/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/aya/opt/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aya/GIT/MinkowskiEngine/examples/reconstruction.py", line 44, in <module>
    import MinkowskiEngine as ME
  File "/Users/aya/GIT/MinkowskiEngine/MinkowskiEngine/__init__.py", line 35, in <module>
    from SparseTensor import SparseTensor, SparseTensorOperationMode, \
  File "/Users/aya/GIT/MinkowskiEngine/MinkowskiEngine/SparseTensor.py", line 34, in <module>
    from MinkowskiCoords import CoordsKey, CoordsManager
  File "/Users/aya/GIT/MinkowskiEngine/MinkowskiEngine/MinkowskiCoords.py", line 31, in <module>
    import MinkowskiEngineBackend as MEB

ImportError: dlopen(/Users/aya/opt/anaconda3/envs/py3-mink/lib/python3.7/site-packages/MinkowskiEngine-0.4.2-py3.7-macosx-10.9-x86_64.egg/MinkowskiEngineBackend.cpython-37m-darwin.so, 2): Symbol not found: __ZNK2at6Tensor8data_ptrIlEEPT_v
  Referenced from: /Users/aya/opt/anaconda3/envs/py3-mink/lib/python3.7/site-packages/MinkowskiEngine-0.4.2-py3.7-macosx-10.9-x86_64.egg/MinkowskiEngineBackend.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/aya/opt/anaconda3/envs/py3-mink/lib/python3.7/site-packages/MinkowskiEngine-0.4.2-py3.7-macosx-10.9-x86_64.egg/MinkowskiEngineBackend.cpython-37m-darwin.so
`

I using a Macbook Pro 16 with Catalina.

any idea ?

thanks.

**Comment by chrischoy** [comment]
Currently, I'm trying to support Mac OS, but I'm also stuck on this error too.

**Comment by liaopeiyuan** [comment]
try converting your long declarations to int64_t

**Comment by nicolas-chaulet** [comment]
This solved it for me on another repo!! Thank you so much :)

**Comment by BigZSmallY** [comment]
it works!

**Comment by jasonperhaps** [comment]
> try converting your long declarations to int64_t

Amazing! Tested and It works in OpenPCDet repo!

**Comment by danielhavir** [comment]
What do you mean by `converting your long declarations to int64_t` ? How did you achieve that?

**Comment by austingreisman** [comment]
For anyone else still looking at this ticket, switching between `pip` and `conda` was causing me problems.
There's a command for installing open3d with `conda` instead of `pip` 

`conda install -c open3d-admin open3d`

[Source Link](https://anaconda.org/open3d-admin/open3d)
