### ISSUE TITLE
'MinkowskiEngineBackend.CoordsManager' object has no attribute 'getKernelMapGPU'

### ISSUE THREAD

**Issue by iliesaya** [NVIDIA/MinkowskiEngine#107]
I am following https://stanfordvl.github.io/MinkowskiEngine/demo/sparse_tensor_reconstruction.html 
on a ubuntu 18 virtual machine, under Conda : 

(py3-mink) aya@ubuntu:~/GIT/MinkowskiEngine$ **python -m examples.reconstruction --train**

ubuntu 03/22 12:27:55 Namespace(batch_size=16, load_optimizer='true', lr=0.01, max_iter=30000, max_visualization=4, momentum=0.9, num_workers=1, resolution=128, stat_freq=50, train=True, val_freq=1000, weight_decay=0.0001, weights='modelnet_reconstruction.pth')
ubuntu 03/22 12:27:55 Loading the subset val from ./ModelNet40 with 889 files
ubuntu 03/22 12:27:56 GenerativeNet(
  (block1): Sequential(
    (0): MinkowskiConvolutionTranspose(in=889, out=1024, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=1024, out=1024, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
    (6): MinkowskiConvolutionTranspose(in=1024, out=512, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (7): MinkowskiBatchNorm(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (8): MinkowskiELU()
    (9): MinkowskiConvolution(in=512, out=512, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (10): MinkowskiBatchNorm(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (11): MinkowskiELU()
  )
  (block1_cls): MinkowskiConvolution(in=512, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block2): Sequential(
    (0): MinkowskiConvolutionTranspose(in=512, out=256, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=256, out=256, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block2_cls): MinkowskiConvolution(in=256, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block3): Sequential(
    (0): MinkowskiConvolutionTranspose(in=256, out=128, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=128, out=128, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block3_cls): MinkowskiConvolution(in=128, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block4): Sequential(
    (0): MinkowskiConvolutionTranspose(in=128, out=64, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block4_cls): MinkowskiConvolution(in=64, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block5): Sequential(
    (0): MinkowskiConvolutionTranspose(in=64, out=32, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=32, out=32, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block5_cls): MinkowskiConvolution(in=32, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block6): Sequential(
    (0): MinkowskiConvolutionTranspose(in=32, out=16, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=16, out=16, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block6_cls): MinkowskiConvolution(in=16, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (pruning): MinkowskiPruning()
)
ubuntu 03/22 12:27:56 LR: [0.01]
Traceback (most recent call last):
  File "/home/aya/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aya/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aya/GIT/MinkowskiEngine/examples/reconstruction.py", line 613, in <module>
    train(net, dataloader, device, config)
  File "/home/aya/GIT/MinkowskiEngine/examples/reconstruction.py", line 507, in train
    out_cls, targets, sout = net(sin, target_key)
  File "/home/aya/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aya/GIT/MinkowskiEngine/examples/reconstruction.py", line 377, in forward
    target = self.get_target(out1, target_key)
  File "/home/aya/GIT/MinkowskiEngine/examples/reconstruction.py", line 360, in get_target
    region_type=1)
  File "/home/aya/GIT/MinkowskiEngine/MinkowskiEngine/MinkowskiCoords.py", line 263, in get_kernel_map
    if on_gpu else self.CPPCoordsManager.getKernelMapGPU
**AttributeError: 'MinkowskiEngineBackend.CoordsManager' object has no attribute 'getKernelMapGPU'**

when I am skipping the train part :
**python -m examples.reconstruction**

and after adding in torch.load map_location=torch.device('cpu') , I have the same error message 

**AttributeError: 'MinkowskiEngineBackend.CoordsManager' object has no attribute 'getKernelMapGPU'**

I don't have an Nvidia gpu, and I installed with : **python setup.py install --cpu_only**

Did I miss something?

Thanks.

EDIT :

Checked some history  of **MinkowskiEngine/MinkowskiCoords.py** 

and replaced 

` kernel_map_fn = self.CPPCoordsManager.getKernelMapGPU \
        kernel_map = self.CPPCoordsManager.getKernelMap(	            if on_gpu else self.CPPCoordsManager.getKernelMapGPU
        kernel_map = kernel_map_fn(`

with 

` kernel_map = self.CPPCoordsManager.getKernelMap(`

examples.reconstruction is now running correctely

**Comment by chrischoy** [comment]
I just pushed a fix on it.

Could you install from the latest commit?

Also, this only happens if you use CPU_ONLY build. If torch cannot detect a gpu, it will automatically use CPU_ONLY. Can you confirm that you only have CPUs?
