### ISSUE TITLE
Minkowski Engine integration 😋

### ISSUE THREAD

**Issue by tchaton** [NVIDIA/MinkowskiEngine#109]
Dear people,

Our framework now supports Minkowski Engine 😋
Thanks you again for such a great framework.
I still need to add Unet in Compact API.

Here is the PR:
https://github.com/nicolas-chaulet/deeppointcloud-benchmarks/pull/194#event-3157294167

**Comment by chrischoy** [comment]
Great work! Thanks for letting us know.
