### ISSUE TITLE
How to perform low resolution segmentation

### ISSUE THREAD

**Issue by 519830100** [NVIDIA/MinkowskiEngine#111]
Thanks for sharing the code. I want to ask how to get the ground truth label if the output is 4s feature map, (ie. how to get the 4s ground truth)

**Comment by chrischoy** [comment]
It selects a label randomly within the voxel. Other ways to select label would be selecting argmax, or using the label distribution itself. However, currently these alternatives are not implemented yet.

**Comment by 519830100** [comment]
I don't know if I put it clear. I want to build an FPN architecture, and I want to know the instance or semantic label for every output tower. Is there any fast implementation that I can refer to?

**Comment by chrischoy** [comment]
I see. It is a bit tricky to implement such models, but it is possible with [`get_kernel_map`](https://stanfordvl.github.io/MinkowskiEngine/coords.html#MinkowskiEngine.CoordsManager.get_coords_map) with kernel size 1 and [`sparse_quantize`](https://stanfordvl.github.io/MinkowskiEngine/utils.html#MinkowskiEngine.utils.sparse_quantize).

First, you use the sparse quantize with quantization 4*s to create labels and associate coordiates. At the last layer that you compute loss, you reorder the coordinates with `get_kernel_map`.
