### ISSUE TITLE
About Devoxelization in MinkowskiEngine

### ISSUE THREAD

**Issue by baifanxxx** [NVIDIA/MinkowskiEngine#114]
Hi chrischoy,

Now I use the MinkowskiEngine to build my own semantic segmentation model, but I want to devoxelize the sparse tensor (coords, features) to the original points coords and features. Of course, the feature processing for different points which are in the same voxel can be interpolation or other ways. 
For example, the raw points are [ coords = [[0.1,1.1], [0.2,1.2]]   features = [[1], [2]] ], we can get the sparse tensor [ coords = [[0,1]]  features = [[1]] ] , after the feature extraction, the output is  
[ coords = [[0,1]]  features = [[1,2,3]] ]. Now, I want to convert the voxelize point coords to the raw point coords, to get output [ coords = [[0.1,1.1], [0.2,1.2]]  features = [[1,2,3], [1,2,3]] ] , that is devoxelize. I don't know if there is a devoxelize operation in MinkowskiEngine?

**Comment by chrischoy** [comment]
Currently, it does not.

What I did was, I simply find the nearest neighboring voxel center from a raw point.
However, linear interpolation is one of the features I'm trying to implement.

**Comment by hua-wu-que** [comment]
> Currently, it does not.
> 
> What I did was, I simply find the nearest neighboring voxel center from a raw point.
> However, linear interpolation is one of the features I'm trying to implement.

Hi @chrischoy , how did you find the nearest neighboring voxel center? is there any code for reference? thank you in advance!

**Comment by chrischoy** [comment]
Correct, if you use the slice function, all points in the same voxel will have the same feature.
