### ISSUE TITLE
Why Multi-GPU training is relatively complex

### ISSUE THREAD

**Issue by fengziyue** [NVIDIA/MinkowskiEngine#118]
Hi @chrischoy :

Why the multi GPU scheme is relatively complex than the conventional PyTorch project? I mean in conventional PyTorch project, we just need to add "model=torch.nn.DataParallel(model)", but in the Minkowski engine, we have to modify so many lines of code?

**Comment by chrischoy** [comment]
The DDP example is added. This requires wrapping a model with DDP.
https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu_ddp.py
