### ISSUE TITLE
Error in pruning

### ISSUE THREAD

**Issue by jbjeong** [NVIDIA/MinkowskiEngine#133]
Hello, thank you for the great code.

I encountered an error in pruning like this.

![스크린샷, 2020-04-28 15-08-39](https://user-images.githubusercontent.com/30853761/80460631-12529a80-896f-11ea-911e-384d04be0361.png)

Well, my code is based on the example code 'examples/reconsruction.py'.
If there is SparseTensor 'A',
In the middle of the forward function of Net, I added some line of code that creates the SparseTensor 'B' which has the same coordinate of 'A'.
Then, concatenated the 'A' and 'B'.

```python
B = ME.SparseTensor(
feats_B,
coords=A.C
coords_man=A.coords_man,
corod_key=A.coords_key,
force_creation=True)

out = ME.cat(A, B)

# ...
# out = self.pruning(out, keep)
# ...
```

After, update with this commit (fb95f938c9659c9b32a6884f0da411d5a903853c),
the error has occurred.

**Comment by chrischoy** [comment]
Could you put a complete working example somewhere in the cloud that I can access?
