### ISSUE TITLE
Subsets of Kernel In-Out map keys

### ISSUE THREAD

**Issue by gzamps** [NVIDIA/MinkowskiEngine#141]
Hello and thank you for the library!

I am trying to avoid coordinate mapping re-calculation overheads.
So, given a ME.SparseTensor A, with computed Kernel In-Out map keys for a set of operations, is it possible to extract the kernel In-Out map keys for another ME.SparseTensor B, with B.feats/coords being a **subset** of A.feats/coords, without re-computing them (to save time)?  

I believe the Kernel In-Out Map keys for B are contained in the Kernel In-Out map keys of A, but I could not come up with a solution to extract them, without re-computing.

Thanks in advance!

**Comment by chrischoy** [comment]
Kernel maps are cached automatically once they are created. The copy from the memory to pytorch is the only overhead which is quite cheap.
