### ISSUE TITLE
Generating new coordinates gives coordinates centered around origin.

### ISSUE THREAD

**Issue by dkoh0207** [NVIDIA/MinkowskiEngine#142]
Hello again. While I was trying to implement a 3d autoencoder based on your `reconstruction.py` example, I found out that when new coordinates are generated from a 0-dimensional latent vector (as in the reconstruction example), the coordinates are centered with respect to the origin (0,0,0). 

For example, my target coordinates are given by:

```
tensor([[ 14, 256, 256,   0],
        [ 11, 256, 256, 256],
        [  5, 512, 512,   0],
        ...,
        [ 31, 512,   0, 256],
        [ 14,   0,   0, 512],
        [ 22, 256, 256, 512]], dtype=torch.int32)
```
while the generated coordinates (that correspond to the same stride or spatial resolution) are given as:
```
tensor([[  26, -256, -256, -256],
        [  26,    0, -256, -256],
        [  26,  256, -256, -256],
        ...,
        [  22, -256,  256,  256],
        [  22,    0,  256,  256],
        [  22,  256,  256,  256]], dtype=torch.int32)
```

Due to this coordinate misalignment, there seems to be a large portion of the image where the network cannot reconstruct any voxels in the target image, whereas in regions where they do overlap the reconstruction quality seems reasonable. Do you happen to know a possible cause of this issue? Thanks in advance.

**Comment by chrischoy** [comment]
The latent vectors are generated from the origin because that's how the code was written.

https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/reconstruction.py#L486

the `init_coords` is set to 0.
You have to compute how the receptive field will be defined at the output and align the target. Ohe network cannot predict what you want.
