### ISSUE TITLE
very slow when adding two large sparse tensors

### ISSUE THREAD

**Issue by rancheng** [NVIDIA/MinkowskiEngine#157]
I implemented a U-Net shaped network based on Minkowski Engine, but when run into the following code it takes around `10s`:
```python
dec_4 = self.dec_4_conv(dec_3 + enc_1)
```

Here's the two tensor's size:
```python
In[2]: dec_3.C.shape
Out[2]: torch.Size([1325560, 4])
In[3]: enc_1.C.shape
Out[3]: torch.Size([17083, 4])
```

what I found in the coordinate manager is that it is using `for loops` to merge two coordinate tables:
https://github.com/StanfordVL/MinkowskiEngine/blob/b683e25a2482f49ea851dc4c629ffffdf70e0e37/src/coords_manager.cpp#L151-L182

Is there any way I can speed this part of code? in current speed, the training will take `900h` to finish 50 epoch.

**Comment by chrischoy** [comment]
That is a copy logic for getting the coordinate map to the python side.
There's a way to speed things up by combining the union coordinate generation (https://github.com/StanfordVL/MinkowskiEngine/blob/b683e25a2482f49ea851dc4c629ffffdf70e0e37/src/coordsmap.cpp#L426) and kernel map generation (https://github.com/StanfordVL/MinkowskiEngine/blob/b683e25a2482f49ea851dc4c629ffffdf70e0e37/src/coordsmap.cpp#L426) into one function, which I did not to be consistent with other functions.

**Comment by rancheng** [comment]
by `kernel map generation`, do you mean:
https://github.com/StanfordVL/MinkowskiEngine/blob/b683e25a2482f49ea851dc4c629ffffdf70e0e37/src/coordsmap.cpp#L466-L569

**Comment by chrischoy** [comment]
No, one I referenced on the previous comment.
union map kernel map generation uses a specialized logic since the region size is 1.
