### ISSUE TITLE
very slow speed compared to dense 3d conv

### ISSUE THREAD

**Issue by hua-wu-que** [NVIDIA/MinkowskiEngine#158]
Hi Choy,

After switching to sparse 3d convolution from dense 3d convolution, I found the speed to be around 10 times slower. 

After checking the time spent, I found:

55% time is spent on sparse net forward, 
20% time is spent on sparse tensor pruning. 
7% time is spent on creating the sparseTensor.
 
In my case, increase the batch size does not increase the speed but slow it down. (0.8 example per sec --> 0.6 example per sec after changing batch size from 2 -> 4). Moreover, using multi-gpu (I tried 2gpu and 3gpu) also does not show any improvement in effective number of example/per sec. 

I wonder could you give me some suggestions on how to improve the training speed. And could you share some rough numbers on how long does the training take on typical tasks(like scannet segmentation)?

**Comment by chrischoy** [comment]
Are you using the same network architecture for dense and sparse?
Are you using the same resolution?

Also, random access is not possible on a sparse tensor and that is why it incurs an overhead to manage coordinates in the sparse network. Thus, the efficiently decrease if you use smaller network with small data. The efficiency can be reasonable only if you have deep network with extremely large point clouds.

Also, some operations are CPU intensive and should adjust the OMP_NUM_THREADS to a reasonable level as explained in the readme.

**Comment by xmyqsh** [comment]
@chrischoy 
[convolution.cu](https://github.com/StanfordVL/MinkowskiEngine/blob/master/src/convolution.cu)
 is wonderful except that the following two lines could be optimized by processing the `remainder` separately.
```
As[ty][tx] = ((s + tx) < wA && y < hA) ? A[wA * in_row + s + tx] : 0;
Bs[ty][tx] = ((s + ty) < hB && x < wB) ? B[wB * (s + ty) + x] : 0;
```

By the way, for the in-out maps generation, will `copyInOutMapsToGPU` be the bottleneck? How about generating it by GPU like [spconv](https://github.com/traveller59/spconv/blob/master/src/spconv/indice.cu) does?
