### ISSUE TITLE
Any plan with GPU hashtable?

### ISSUE THREAD

**Issue by BestSonny** [NVIDIA/MinkowskiEngine#161]
@chrischoy Curious about whether you have any plan to implement a GPU-based hashtable?

Is it a reasonable choice?

**Comment by chrischoy** [comment]
Yes, currently under development. Will be released in a few weeks.

**Comment by BestSonny** [comment]
@chrischoy Thanks for the info. This is very helpful. Haha, I'll just wait now...

**Comment by xmyqsh** [comment]
@chrischoy Wonderful!
spconv's GPU based HashTable is fast and memory friendly but not stable...

**Comment by BestSonny** [comment]
@chrischoy  Actually, do you have any channel (e.g. in slack) for discussing anything (e.g. dev, doc, new feats) related to MinkowskiEngine?

**Comment by chrischoy** [comment]
I created a slack channel.
https://join.slack.com/share/zt-ez7azo13-aGm5wXIGQJ~ft6wvjMEkUQ

**Comment by chrischoy** [comment]
Yes, we have a gitter channel https://gitter.im/MinkowskiEngineGitter/general

**Comment by chrischoy** [comment]
Closing since it is available at v0.5.
