### ISSUE TITLE
Small mistake in the documentation

### ISSUE THREAD

**Issue by aniqueakhtar** [NVIDIA/MinkowskiEngine#172]
Hello,
Just wanted to let you know. There's a small mistake at the Kernel Map section of Terminology page:
https://stanfordvl.github.io/MinkowskiEngine/terminology.html
This:
```
Kernel B: 1 → 0
Kernel B: 0 → 2
Kernel H: 2 → 3
Kernel I: 0 → 2
```
should be this according to the example:
```
Kernel B: 1 → 0
Kernel B: 0 → 2
Kernel H: 2 → 3
Kernel I: 0 → 0
```

Thank you for all your help!

**Comment by chrischoy** [comment]
Ah thanks :)

**Comment by chrischoy** [comment]
Fixed on the master and closing the issue.
