### ISSUE TITLE
What is the difference between conv and pool layer on generating the kernel map with same setting?

### ISSUE THREAD

**Issue by xmyqsh** [NVIDIA/MinkowskiEngine#175]
What is the difference between conv and pool layer on generating the kernel map with the same setting?

For example, both conv and pool layer has `kernel size == strides == 4`.

Will pool layer be faster on generating the kernel map with the same setting `kernel size == strides == 4` than conv layer?

This question is about the following statement in the doc:
```
Strided pooling layers for high-dimensional spaces
In extremely high-dimensional spaces, it is very expensive to use strided convolution. Using a cross-shaped kernel is not a good solution for hierarchical maps as everything is very sparse in high-dimensional spaces and cross shaped kernel will end up being empty. Instead, use a pooling layer to create kernel map efficiently and fast.

If you use a pooling layer with kernel size == strides, the MinkowskiEngine will generate kernel map very efficiently as the mapping becomes trivial.
```

**Comment by chrischoy** [comment]
The kernel maps required for pooling and convolution are different since pooling does not require knowing the kernel offset. Thus even when pooling is faster with this setup, you cannot use that kernel map for convolution.
