### ISSUE TITLE
TypeError: rotate(): incompatible function arguments when run reconstruction example

### ISSUE THREAD

**Issue by asurada404** [NVIDIA/MinkowskiEngine#180]
Hello, thanks for your wonderful work.
I have some problems when I run the following example.
`
python -m examples.reconstruction
`
running on the following configuration:
Ubuntu 18.04.2 LTS 
torch version 1.5.1
torchvision version 0.0.1

(mink) liuyi@goodnews:~/projects/mink/MinkowskiEngine$ python -m examples.reconstruction
goodnews 07/06 09:53:11 Namespace(batch_size=16, load_optimizer='true', lr=0.01, max_iter=30000, max_visualization=4, momentum=0.9, num_workers=1, resolution=128, stat_freq=50, train=False, val_freq=1000, weight_decay=0.0001, weights='modelnet_reconstruction.pth')
goodnews 07/06 09:53:11 Loading the subset val from ./ModelNet40 with 889 files
goodnews 07/06 09:53:14 GenerativeNet(
  (block1): Sequential(
    (0): MinkowskiConvolutionTranspose(in=889, out=1024, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=1024, out=1024, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
    (6): MinkowskiConvolutionTranspose(in=1024, out=512, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (7): MinkowskiBatchNorm(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (8): MinkowskiELU()
    (9): MinkowskiConvolution(in=512, out=512, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (10): MinkowskiBatchNorm(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (11): MinkowskiELU()
  )
  (block1_cls): MinkowskiConvolution(in=512, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block2): Sequential(
    (0): MinkowskiConvolutionTranspose(in=512, out=256, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=256, out=256, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block2_cls): MinkowskiConvolution(in=256, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block3): Sequential(
    (0): MinkowskiConvolutionTranspose(in=256, out=128, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=128, out=128, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block3_cls): MinkowskiConvolution(in=128, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block4): Sequential(
    (0): MinkowskiConvolutionTranspose(in=128, out=64, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block4_cls): MinkowskiConvolution(in=64, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block5): Sequential(
    (0): MinkowskiConvolutionTranspose(in=64, out=32, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=32, out=32, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block5_cls): MinkowskiConvolution(in=32, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (block6): Sequential(
    (0): MinkowskiConvolutionTranspose(in=32, out=16, region_type=RegionType.HYPERCUBE, kernel_size=[2, 2, 2], stride=[2, 2, 2], dilation=[1, 1, 1])
    (1): MinkowskiBatchNorm(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiELU()
    (3): MinkowskiConvolution(in=16, out=16, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (4): MinkowskiBatchNorm(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiELU()
  )
  (block6_cls): MinkowskiConvolution(in=16, out=1, region_type=RegionType.HYPERCUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (pruning): MinkowskiPruning()
)
goodnews 07/06 09:53:14 Loading weights from modelnet_reconstruction.pth
Traceback (most recent call last):
  File "/home/liuyi/.conda/envs/mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liuyi/.conda/envs/mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liuyi/projects/mink/MinkowskiEngine/examples/reconstruction.py", line 625, in <module>
    visualize(net, dataloader, device, config)
  File "/home/liuyi/projects/mink/MinkowskiEngine/examples/reconstruction.py", line 580, in visualize
    pcd.rotate(M)
TypeError: rotate(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d_pybind.geometry.Geometry3D, R: numpy.ndarray[float64[3, 3]], center: numpy.ndarray[float64[3, 1]]) -> open3d.open3d_pybind.geometry.Geometry3D

Invoked with: geometry::PointCloud with 25858 points., array([[ 0.80656762, -0.5868724 , -0.07091862],
       [ 0.3770505 ,  0.418344  ,  0.82632997],
       [-0.45528188, -0.6932309 ,  0.55870326]])

**Comment by chrischoy** [comment]
I see. It seems that the visualization tool (open3d) updated the API. Thanks for reporting the issue.

**Comment by rancheng** [comment]
> I see. It seems that the visualization tool (open3d) updated the API. Thanks for reporting the issue.

The bug was fixed, they updated their rotate function with a rotation center parameter. `pcd.rotate(R, center)`
