### ISSUE TITLE
Document update needed for the installation

### ISSUE THREAD

**Issue by lilanxiao** [NVIDIA/MinkowskiEngine#183]
Hi, 

I tried to use the most recent code (commit 423f526) to install MinkowskiEngine. I used Conda enviroment for the installation. After I ran `python setup.py install --install-option="--blas=mkl"` following the README, I got 
```
Traceback (most recent call last):
  File "setup.py", line 153, in <module>
    assert BLAS in BLAS_LIST
AssertionError
```
I printed the variable `BLAS` and got `--blas=`, which was obviously unexpected. I think it might be related to the commit 411b5ebdf16c598ba57bece89b6a2729b56c45ea

This commit seems to have changed the usage of `setup.py`. As the new added comments suggests, the validate usage now should be:

`python setup.py install --blas=mkl`

Using this command I finished the installation without any issue. Not a big problem but it indeed confused me for a while. At first I thought my MKL is broken. A Docu update would be nice :)

Thank you!

**Comment by chrischoy** [comment]
Thanks for the issue. Will update the document.

**Comment by chrischoy** [comment]
For pip installation

```
pip install --install-option="--blas=openblas"
```

For python setup installation

```
python setup.py install --blas=openblas
```
