### ISSUE TITLE
Why did the visualize function in `examples.reconstruction` also need the sampling points to generate the target sparse tensor?

### ISSUE THREAD

**Issue by asurada404** [NVIDIA/MinkowskiEngine#186]
Why did the visualize function in `examples.reconstruction` also need the sampling points to generate the target sparse tensor?
https://github.com/NVIDIA/MinkowskiEngine/blob/423f526c0cd0d8791f766e81ae70ee728d00c2cb/examples/reconstruction.py#L561
Did the visualize function in `examples.reconstruction` equal to inference the object structure by the object index?

**Comment by chrischoy** [comment]
I don't understand, but the function takes the input since I'm using the same forward pass function for training and testing. However, for testing, the target sparse tensor is ignored except for the evaluation.
