### ISSUE TITLE
Would quantization still work without using sparse_quantize

### ISSUE THREAD

**Issue by aniqueakhtar** [NVIDIA/MinkowskiEngine#190]
If I use my own quantization scheme by dividing the coords by 2. Would it still work?
What if there's a translation of 1 introduced during custom quantization. Would this function and the subsequent convolutions still work.
e.g.
```
coords = coords/2 + 1
x = ME.SparseTensor(feats=feats, coords=coords, tensor_stride=2)
```
Thank you.

**Comment by aniqueakhtar** [comment]
And along the same lines, what would happen if I initiate a Sparse Tensor:
`x = ME.SparseTensor(feats=feats, coords=coords, tensor_stride=2)`
Which is not quantized to a stride 2?
Would the occupied values in the coordinates that are odd be omitted by the convolutions?
Thank you.

**Comment by chrischoy** [comment]
It depends on the quantization mode. https://nvidia.github.io/MinkowskiEngine/sparse_tensor.html#MinkowskiEngine.SparseTensor.SparseTensor.__init__

**Comment by chrischoy** [comment]
You have to make sure that the coordinates have tensor stride 2 when you set it to 2. Theres no check for speed.

**Comment by aniqueakhtar** [comment]
I see.
Since the default quantization method is subsample.
```
coords1 = coords/2 + 1
x1 = ME.SparseTensor(feats=feats, coords=coords1, tensor_stride=2)
coords2 = coords/2
x2 = ME.SparseTensor(feats=feats, coords=coords2, tensor_stride=2)
```
So `x1` would be different from `x2`
But if
`feats = np.expand_dims(np.ones(coords.shape[0]), 1)`
Then I believe `x1` and `x2` would be similar, even if the coordinates are shifted by 1.
Correct me if I am wrong.

Thank you.

**Comment by chrischoy** [comment]
Yes. they will be similar but not the same. but it is better than 1024 point random subsampling.
