### ISSUE TITLE
‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’

### ISSUE THREAD

**Issue by DapengFeng** [NVIDIA/MinkowskiEngine#193]
`In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/union.hpp:28,
                 from src/union.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/coords_manager.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_avg.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_transpose.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_max.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/convolution_transpose.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/broadcast.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_global_avg.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pruning.hpp:28,
                 from src/pruning.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/coords_key.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_global_max.cpp:21:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:18: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                  ^
Makefile:162: recipe for target 'objs/union.o' failed
make: *** [objs/union.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:162: recipe for target 'objs/coords_manager.o' failed
make: *** [objs/coords_manager.o] Error 1
Makefile:162: recipe for target 'objs/pooling_avg.o' failed
make: *** [objs/pooling_avg.o] Error 1
Makefile:162: recipe for target 'objs/pooling_transpose.o' failed
make: *** [objs/pooling_transpose.o] Error 1
Makefile:162: recipe for target 'objs/broadcast.o' failed
make: *** [objs/broadcast.o] Error 1
Makefile:162: recipe for target 'objs/pooling_max.o' failed
make: *** [objs/pooling_max.o] Error 1
Makefile:162: recipe for target 'objs/convolution_transpose.o' failed
make: *** [objs/convolution_transpose.o] Error 1
Makefile:162: recipe for target 'objs/pruning.o' failed
make: *** [objs/pruning.o] Error 1
Makefile:162: recipe for target 'objs/coords_key.o' failed
make: *** [objs/coords_key.o] Error 1
Makefile:162: recipe for target 'objs/pooling_global_avg.o' failed
make: *** [objs/pooling_global_avg.o] Error 1
Makefile:162: recipe for target 'objs/pooling_global_max.o' failed
make: *** [objs/pooling_global_max.o] Error 1`

**Comment by DapengFeng** [comment]
It seems that this repo does not support PyTorch 1.4, and I try to upgrade the PyTorch version.

**Comment by Xavier-wa** [comment]
same problem, could you tell me the envs (e.g. the version of torch,cuda ,minkowski and so on) plz
