### ISSUE TITLE
Suspicious code in CoordsManager.create_coords_key

### ISSUE THREAD

**Issue by SergioRAgostinho** [NVIDIA/MinkowskiEngine#194]
I was crawling through the code when I found the following
https://github.com/NVIDIA/MinkowskiEngine/blob/2bb627e9e395419ac9f0289c3517b1c0c00500bd/MinkowskiEngine/MinkowskiCoords.py#L132-L148

The arguments `force_creation`, `force_remap` and `allow_duplicate_coords` are not being used in the method's body and it looks like they should be propagated down.

-----
This is something completely orthogonal, but I bumped into the snippet above while trying to find an efficient way of getting coordinate mapping that takes place between `coords` and `out` in my pseudo-example below. `coords` will occasionally have repeated coordinates and I was looking for some info in the coordinate manager which pinpoints which elements in `coord` were repeated.

```python
# coords is a torch.IntTensor
# in is a SparseTensor
# mconv is a MinkowskiConvolution
out = mconv.forward(in, coords) 
```
if you have good recommendations to solve my original problem please chime in.  :)

**Comment by chrischoy** [comment]
The force_creation, allow_duplicate_coords, force_remap will be deprecated from v0.5
