### ISSUE TITLE
Allow python version to be set from setup.py

### ISSUE THREAD

**Issue by CCInc** [NVIDIA/MinkowskiEngine#195]
In the environment I'm trying to install Minkowski in, `python` refers to `python2` which does not have my torch installation. Can we add a command line option to the pip installation to change which `PYTHON` in the makefile is executed? Thanks!

**Comment by axelcournac** [comment]
Did you tried `pip3` or `python3 setup.py install` ?
Check if python is in your conda:
`conda search python`
Also: to create the new environment for Python 3.6, in your terminal window or an Anaconda Prompt, run:
`conda create -n py36 python=3.6 anaconda`
Replace py36 with the name of the environment you want to create.

**Comment by CCInc** [comment]
Due to the way my environment is set up, it would be inconvenient to create a separate environment for python 3. I ended up redirecting `python` to point to `python3` but I think this isn't the ideal solution. But I suppose it isn't a common issue. Thanks!

**Comment by chrischoy** [comment]
The Makefile compilation will be deprecated from v0.5.
