### ISSUE TITLE
Question about OMP_NUM_THREADS

### ISSUE THREAD

**Issue by DapengFeng** [NVIDIA/MinkowskiEngine#196]
Hi @chrischoy, thanks for your excellent works. But I found that it is hard for me to set the OMP_NUM_THREADS to acquire a high-performance speed when using a distributed training scheme across 8 Nvidia Tesla V-100 32G with 96 CPU cores.  Could you give some tips on setting the number of OMP_NUM_THREADS to acquire a high speed?

**Comment by chrischoy** [comment]
I don't know a good alternative for this either. I tried to programmatically set the num threads, but didn't work.

However, you might want to try [v0.5 preview](https://github.com/NVIDIA/MinkowskiEngine/tree/v0.5) which does everything on GPU thus it does not rely on OMP_NUM_THREADS.

**Comment by DapengFeng** [comment]
Thanks.
