### ISSUE TITLE
Did ME.MinkowskiPruning() run on CPU? If So, Did it will decease the utilization of GPU?

### ISSUE THREAD

**Issue by asurada404** [NVIDIA/MinkowskiEngine#198]
In ME.MinkowskiPruning(SparseTensor, mask), [the mask must be a CPU tensor](https://github.com/NVIDIA/MinkowskiEngine/blob/2bb627e9e395419ac9f0289c3517b1c0c00500bd/MinkowskiEngine/MinkowskiPruning.py#L39).
In [completion](https://github.com/NVIDIA/MinkowskiEngine/blob/2bb627e9e395419ac9f0289c3517b1c0c00500bd/examples/completion.py#L396) demo, the Pruning operation will be done multi times. Did it break the GPU process and decrease the utilization of GPU?

**Comment by chrischoy** [comment]
The v0.4.3 coordinate manager uses the CPU hash table for all coordinate related operations, but all non-coordinate related operations are done on GPU. Same for convolution/pooling/etc.
