### ISSUE TITLE
Question about the coordinates after the convolution

### ISSUE THREAD

**Issue by yingzhang1109** [NVIDIA/MinkowskiEngine#199]
I notice that when I am doing the convolutions, the coordinates are disordered among the batch. for example,
SparseTensor(
  Coords=tensor([[  1, 120,  28,  80],
        [  3,  16,  76,  16],
        [  3,  24,  96,   0],
        ...,
        [  1,  92, 100,  32],
        [  1,  28,  84,  72],
        [  1,  20,  40,   0]], dtype=torch.int32))

It is quite confusing for me when I am doing the deconvolution. I am wondering if there is a way to keep the coordinates always in the same order?

**Comment by chrischoy** [comment]
You don't have to do anything manually to make conv/deconv work as expected.
The orders are random since a hash table is managing the coordinates.

Are you asking if there's a way to print this for debugging purpose?

**Comment by yingzhang1109** [comment]
what if I want to concatenate it with a self-define sparse tensor, and how should I know I assign the correct value for the batch?

**Comment by yingzhang1109** [comment]
I think my question is if I concatenate it with another sparse tensor, I can apply the same coords_manager and coords_key, but for features, should I place it in the order of the batch or should I place it according to the coordinates shown here:
Coords=tensor([[ 1, 120, 28, 80],
[ 3, 16, 76, 16],
[ 3, 24, 96, 0],
...,
[ 1, 92, 100, 32],
[ 1, 28, 84, 72],
[ 1, 20, 40, 0]], dtype=torch.int32))
since for here, the batches are disorganized, it's quite hard for me to generate it.

**Comment by chrischoy** [comment]
You should not modify the coordinates directly since it won't actually update the MinkowskiEngine backend.
The MinkowskiEngine provides the union function for this.

Also, I'll probably should disable all direct modification of all coordinates to prevent people from doing updates like this.

**Comment by yingzhang1109** [comment]
I havent modified the coordinates. Instead, I want to create another tensor which has new feature values on the same coordinates. I am wondering if I can assign feature values to each batch?

**Comment by chrischoy** [comment]
There's a `MinkowskiBroadcast` function that copies a feature vector to all points in an instance within a batch.
Also, if you want to concatenate, you can use the `MinkowskiBroadcastConcatenation`.

**Comment by yingzhang1109** [comment]
Thanks a lot for your response. That really helps.

**Comment by yingzhang1109** [comment]
Hello, Crischoy, I have another issue. I am wondering if you can help me on that?
I am trying to make a U-NET type model, and I like to concat the original convolution with the transpose convolution. However, I got an error saying that "SparseTensors must have the same coords_key." I printed out the two tensors, and I think they have the same coordinates and the same coords_key. I am wondering if you can provide some suggestion on that?

torch.Size([68814, 32])
SparseTensor(
  Coords=tensor([[  0,   0,  48,  66],
        [  0,  84,  84,  34],
        [  0,  34,  20,  96],
        ...,
        [  0, 106,  54,  76],
        [  0,  86,  62,  32],
        [  0,  60,  36,  10]], dtype=torch.int32)
  Feats=tensor([[ 0.9154, -0.9081, -0.2608,  ..., -0.0861, -0.0167,  0.6300],
        [-0.4195,  0.0492, -0.1208,  ...,  0.4520, -0.9930, -0.3899],
        [ 0.6056,  0.9714, -1.2924,  ..., -0.5428, -2.3724, -0.2446],
        ...,
        [ 1.9427,  2.4919, -1.1154,  ..., -1.0723, -1.3926, -2.8989],
        [-0.0036, -0.7351,  2.8445,  ..., -1.7908, -0.0223,  1.7999],
        [ 0.5379, -0.0176, -0.9784,  ..., -1.9315,  1.0815,  0.4678]],
       device='cuda:0', grad_fn=<CudnnBatchNormBackward>)
  coords_key=< CoordsKey, key: 16908437251554604741, tensor_stride: [2, 2, 2] in dimension: 3 >
  tensor_stride=[2, 2, 2]
  coords_man=< CoordsManager
	Number of Coordinate Maps: 2 
		Coordinate Map Key: 16908437251554604741, Size: 68814 
		Coordinate Map Key: 15034981587763204738, Size: 397227
	Number of Kernel Maps: 3 
		Kernel In-Out Map Key: 13141478664318330487, Size: 1259544 
		Kernel In-Out Map Key: 13453830109827794797, Size: 8586771 
		Kernel In-Out Map Key: 1762389936144326719, Size: 397227 >
  spatial dimension=3)

torch.Size([68814, 32])
SparseTensor(
  Coords=tensor([[  0,   0,  48,  66],
        [  0,  84,  84,  34],
        [  0,  34,  20,  96],
        ...,
        [  0, 106,  54,  76],
        [  0,  86,  62,  32],
        [  0,  60,  36,  10]], dtype=torch.int32)
  Feats=tensor([[0.9400, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.8876],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 1.4767, 0.3951],
        [0.0000, 0.2738, 0.0000,  ..., 0.0000, 0.0000, 1.6549],
        ...,
        [0.3817, 0.0000, 0.0000,  ..., 0.0000, 1.1551, 0.0000],
        [0.8586, 0.0000, 1.1599,  ..., 0.5960, 0.4299, 0.0545],
        [0.9415, 0.0000, 1.6804,  ..., 0.8477, 0.0000, 0.0000]],
       device='cuda:0', grad_fn=<MinkowskiPoolingTransposeFunctionBackward>)
  coords_key=< CoordsKey, key: 16908437251554604741, tensor_stride: [2, 2, 2] in dimension: 3 >
  tensor_stride=[2, 2, 2]
  coords_man=< CoordsManager
	Number of Coordinate Maps: 4 
		Coordinate Map Key: 15658191375538532279, Size: 1 
		Coordinate Map Key: 13165352224437222115, Size: 14649 
		Coordinate Map Key: 15034981587763204738, Size: 397227 
		Coordinate Map Key: 16908437251554604741, Size: 68814
	Number of Kernel Maps: 8 
		Kernel In-Out Map Key: 9095388978914071026, Size: 238007 
		Kernel In-Out Map Key: 6756741679834017479, Size: 68814 
		Kernel In-Out Map Key: 8493642174080105661, Size: 14649 
		Kernel In-Out Map Key: 13453830109827794797, Size: 8586771 
		Kernel In-Out Map Key: 13141478664318330487, Size: 1259544 
		Kernel In-Out Map Key: 670307949683588350, Size: 68814 
		Kernel In-Out Map Key: 1762389936144326719, Size: 397227 
		Kernel In-Out Map Key: 9096345554030425371, Size: 238007 >
  spatial dimension=3)

Traceback (most recent call last):

  File "/home/ying/Desktop/Ying_ubun/highResolution/ManuNet_combineModel2.py", line 258, in <module>
    train(net,device,config)

  File "/home/ying/Desktop/Ying_ubun/highResolution/ManuNet_combineModel2.py", line 184, in train
    sout = net(sin,p)

  File "/home/ying/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/ying/Desktop/Ying_ubun/highResolution/ManuNet_combineModel2.py", line 144, in forward
    out = ME.cat(out,out_s1)

  File "/home/ying/anaconda3/envs/py3-mink/lib/python3.7/site-packages/MinkowskiEngine-0.4.3-py3.7-linux-x86_64.egg/MinkowskiEngine/MinkowskiOps.py", line 72, in cat
    assert coords_key == s.coords_key, COORDS_KEY_DIFFERENT_ERROR

AssertionError: SparseTensors must have the same coords_key.

**Comment by MiZhenxing** [comment]
Hi, I still have a question about the order of features. Since these order are random during convolutions, after I get the output, are there any methods to reordering the output features so that they would have the same roder as the input features? Thank you!
