### ISSUE TITLE
Installation problem: Wrong torch version collected from MinkowskiEngine 

### ISSUE THREAD

**Issue by alessandroscoppio** [NVIDIA/MinkowskiEngine#200]
I use to have a working installation. After updating my torch and cuda respectively, I am not able to install MinkowskiEngine.
pip install works, but not with GPU.
running python setup.py install throws errors.
using the --install-option='--force_cuda" I get something really weird: the torch version collected from MinkowskiEngine appear to be 0.1.2, that does not have any CUDA support (or at least not a torch/cuda package folder).
How to fix this?

My setup is:
Python version: 3.6.9
torch version: 1.6.0
CUDA version: 10.2 (torch.cuda.is_gpu_available() is true)

I tried both the latest source and version 0.4.2, both gave this output:
`/usr/lib/python3/dist-packages/pip/commands/install.py:212: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting MinkowskiEngine==0.4.2
  Downloading https://files.pythonhosted.org/packages/d7/7c/3892a4d9ee70869b900ba06c750943e31c85fc2a165dc483e3b79cd61b39/MinkowskiEngine-0.4.2.tar.gz (108kB)
    100% |████████████████████████████████| 112kB 2.7MB/s 
Collecting torch (from MinkowskiEngine==0.4.2)
  Downloading https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz (128kB)
    100% |████████████████████████████████| 133kB 27.5MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/torch.egg-info
    writing pip-egg-info/torch.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/torch.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/torch.egg-info/requires.txt
    writing top-level names to pip-egg-info/torch.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/torch.egg-info/SOURCES.txt'
    error: package directory 'torch/cuda' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5tqd9vr_/torch/                                                                                        `

**Comment by lilanxiao** [comment]
Have you cuda-toolkit installed on you machine? So far as I known, the installation needs not only the CUDA-driver (you have already checked it by using `torch.cuda.is_gpu_available()` ) but also the `cuda-toolkit`. You can check it with  `apt list | grep cuda` if you are using Ubuntu/Debian. If the `cuda-toolkit` is installed, you would see the packages like: 

```
cuda-toolkit-10-2/unknown,now 10.2.89-1 amd64 [installed]
cuda-tools-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
```

You would probably see some other cuda-staffs like:

```
cuda-nvcc-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvdisasm-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvgraph-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvgraph-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvjpeg-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvjpeg-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvml-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvprof-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvprune-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvrtc-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvrtc-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvtx-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvvp-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01/now 1.0-1 amd64 [installed,local]
cuda-runtime-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-samples-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-sanitizer-api-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
```

If the toolkit is not installed, follow [this page](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) to install it. 

Hope it helps. :smile:

**Comment by alessandroscoppio** [comment]
Hi @lilanxiao , everything looks fine with CUDA installation,
the output of grep cuda is
`caffe-cuda/bionic 1.0.0-6build1 amd64
caffe-tools-cuda/bionic 1.0.0-6build1 amd64
cuda/unknown,now 10.2.89-1 amd64 [installed]
cuda-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-command-line-tools-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-compat-10-2/unknown 440.33.01-1 amd64
cuda-compiler-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-core-10-2/unknown 10.2.89-1 amd64
cuda-cudart-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cudart-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cufft-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cufft-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cuobjdump-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cupti-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cupti-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-curand-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-curand-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cusolver-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cusolver-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cusparse-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-cusparse-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-demo-suite-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-documentation-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-driver-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-drivers/unknown,now 440.33.01-1 amd64 [installed,automatic]
cuda-gdb-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-gdb-src-10-2/unknown 10.2.89-1 amd64
cuda-libraries-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-libraries-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-license-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-memcheck-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-minimal-build-10-2/unknown 10.2.89-1 amd64
cuda-misc-headers-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-npp-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-npp-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nsight-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nsight-compute-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nsight-systems-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvcc-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvdisasm-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvgraph-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvgraph-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvjpeg-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvjpeg-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvml-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvprof-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvprune-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvrtc-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvrtc-dev-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvtx-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-nvvp-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01/now 1.0-1 amd64 [installed,local]
cuda-runtime-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-samples-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-sanitizer-api-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-toolkit-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-tools-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
cuda-visual-tools-10-2/unknown,now 10.2.89-1 amd64 [installed,automatic]
libcaffe-cuda-dev/bionic 1.0.0-6build1 amd64
libcaffe-cuda1/bionic 1.0.0-6build1 amd64
libcuda1-304/bionic 304.137-0ubuntu2 amd64
libcuda1-304-updates/bionic 304.137-0ubuntu2 amd64
libcuda1-331/bionic-updates,bionic 340.108-0ubuntu0.18.04.1 amd64
libcuda1-331-updates/bionic-updates,bionic 340.108-0ubuntu0.18.04.1 amd64
libcuda1-340/bionic-updates,bionic 340.108-0ubuntu0.18.04.1 amd64
libcuda1-340-updates/bionic-updates,bionic 340.108-0ubuntu0.18.04.1 amd64
libcuda1-346/bionic 352.63-0ubuntu3 amd64
libcuda1-346-updates/bionic 352.63-0ubuntu3 amd64
libcuda1-352/bionic 361.45.11-0ubuntu4 amd64
libcuda1-352-updates/bionic 361.45.11-0ubuntu4 amd64
libcuda1-361/bionic 367.57-0ubuntu5 amd64
libcuda1-361-updates/bionic 361.45.11-0ubuntu4 amd64
libcuda1-367/bionic 375.82-0ubuntu3 amd64
libcuda1-375/bionic 384.111-0ubuntu1 amd64
libcuda1-384/bionic-updates,bionic-security 390.138-0ubuntu0.18.04.1 amd64
libcudart9.1/bionic 9.1.85-3ubuntu1 amd64
libcudnn7/now 7.6.5.32-1+cuda10.1 amd64 [installed,local]
nvidia-cuda-dev/bionic 9.1.85-3ubuntu1 amd64
nvidia-cuda-doc/bionic,bionic 9.1.85-3ubuntu1 all
nvidia-cuda-gdb/bionic 9.1.85-3ubuntu1 amd64
nvidia-cuda-toolkit/bionic 9.1.85-3ubuntu1 amd64
`
I see now that last 6 entries have different cuda versions, but I'm not sure that's the problem

**Comment by chrischoy** [comment]
Can you try to install after downloading the ME on your local directory?

pip tends to not print all logs that are crucial for debugging the installation.

```
git clone https://github.com/NVIDIA/MinkowskiEngine
cd MinkowskiEngine
python setup.py install # followed by options
```

**Comment by alessandroscoppio** [comment]
weirdly, installing from source code works. Thanks!
