### ISSUE TITLE
How to get the coords of each batch?

### ISSUE THREAD

**Issue by jimmy15923** [NVIDIA/MinkowskiEngine#202]
I am following the [tutorial](https://nvidia.github.io/MinkowskiEngine/demo/training.html#making-a-dataloader) here to build my dataloader for object classification. However, when I set the batch_size=8, I got the input with approx. 8x times points than batch size=1 instead of the tensor with batch dimension, e.g., (8, num_points, 3).

 In this case, how can I get the group of points of batch 1  (points set for an object)?

```python
train_dataloader = DataLoader(train_dataset, batch_size=1, collate_fn=ME.utils.SparseCollation())
train_iter = iter(train_dataloader)
for i, data in enumerate(train_iter):
    coords, feats, labels = data
    sinput = ME.SparseTensor(feats, coords)
    print(sinput.shape)

## torch.Size([1567, 3])

train_dataloader = DataLoader(train_dataset, batch_size=8, collate_fn=ME.utils.SparseCollation())
train_iter = iter(train_dataloader)
for i, data in enumerate(train_iter):
    coords, feats, labels = data
    sinput = ME.SparseTensor(feats, coords)
    print(sinput.shape)

## torch.Size([17574, 3])
```

**Comment by chrischoy** [comment]
Please refer to the examples/modelnet40.py for the classification. Also, search decomposed_coordinates_and_features for batch wise decomposition.
