### ISSUE TITLE
Questions about the speed of version 0.5

### ISSUE THREAD

**Issue by chronbird** [NVIDIA/MinkowskiEngine#204]
Hi,
A quick question: compared to v0.4, how much faster does v0.5 boost when using cuda kernel generator? Thanks.

**Comment by chrischoy** [comment]
For Mink UNet 14, which has around 20 conv layers show x3-x5 speedup compared with v0.4.3.
![](https://pbs.twimg.com/media/EjHKDdBUcAIUytv?format=png&name=large)

**Comment by chronbird** [comment]
Thanks！
