### ISSUE TITLE
MinkowskiUnion Backprop error

### ISSUE THREAD

**Issue by jethewes** [NVIDIA/MinkowskiEngine#205]
I'm training a two-stack network for a particle physics application, in which two separate views of the same interaction are used to classify each event. The two tensors are passed into separate sparse convolution layers, and are then combined using MinkowskiUnion to produce a single sparse tensor, which is then passed into more sparse convolutions and eventually an event classification. However, the MInkowskiUnion layer throws the following error:

```
RuntimeError: Function MinkowskiUnionFunctionBackward returned an invalid gradient at index 1 - got [14772, 8] but expected shape compatible with [15367, 8] (validate_outputs at ../torch/csrc/autograd/engine.cpp:476)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6c (0x7fee8666f36c in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2bc66ff (0x7feede3cb6ff in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x48f (0x7feede3cc97f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x579 (0x7feede3cea89 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::thread_init(int) + 0x49 (0x7feede3c6569 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::python::PythonEngine::thread_init(int) + 0x48 (0x7feee1673608 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xc819d (0x7feffe75219d in /opt/conda/bin/../lib/libstdc++.so.6)
frame #7: <unknown function> + 0x76db (0x7ff001e1b6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x3f (0x7ff001b4488f in /lib/x86_64-linux-gnu/libc.so.6)
```

Am I making any obvious mistakes here, or misunderstanding the purpose of the MinkowskiUnion layer? I expected this layer to be able to combine tensors with different coordinates, but maybe I'm mistaken. Any help is greatly appreciated!

**Comment by chrischoy** [comment]
Could you please put a minimally reproducible code here?

**Comment by jethewes** [comment]
Apologies for the long delay in responding – I've committed a minimal reproducible example [here](https://github.com/jethewes/minkowski-union-example) that should reproduce the union backprop error.

There's also an error in MinkowskiChannelwiseConvolution included in this example, which is omitted by default – that module is commented out in the model, since it doesn't alter the tensor's shape. Uncommenting will cause a different error to crop up, although if that isn't useful then it can be ignored.

**Comment by chrischoy** [comment]
Thanks for reporting the error. The latest master has fixed the error and I made a [PR](https://github.com/jethewes/minkowski-union-example/pull/1) on your repo as well to fix some errors in your implementation.
