### ISSUE TITLE
Unknown option -extended-lambda (v0.5)

### ISSUE THREAD

**Issue by soCzech** [NVIDIA/MinkowskiEngine#207]
Dont use `--extended-lambda` but rather `--expt-extended-lambda` in [setup.py#L163](https://github.com/NVIDIA/MinkowskiEngine/blob/v0.5/setup.py#L163).

`--extended-lambda` throws error in older `nvcc` and `--expt-extended-lambda` should be equivalent ([nvcc --expt-extended-lambda](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-altering-compiler-linker-behavior-expt-extended-lambda)).

**Comment by chrischoy** [comment]
Which version are you using? The minimum required version is 10.1

**Comment by soCzech** [comment]
I am using 10.1 🙂 It does NOT support `--extended-lambda` (see [docs.nvidia.com/cuda/archive/10.1/cuda-compiler-driver-nvcc](https://docs.nvidia.com/cuda/archive/10.1/cuda-compiler-driver-nvcc/#options-for-altering-compiler-linker-behavior-expt-extended-lambda)).

**Comment by chrischoy** [comment]
Thanks! I updated the setup.py with `--expt-extended-lambda`
