### ISSUE TITLE
'CoordinateManager' object has no attribute 'create_coordinate_map_key' in v0.5

### ISSUE THREAD

**Issue by loiccordone** [NVIDIA/MinkowskiEngine#210]
Hello,

The method 'features_at_coords' can't be called in v0.5:
`query_key = cm.create_coordinate_map_key(query_coords)`
`AttributeError: 'CoordinateManager' object has no attribute 'create_coordinate_map_key'`

Any idea when this will be available?
I'm guessing it's the future "insert() -> CoordinateMapKey" mentionned in the TODO in MinkowskiCoordinateManager.py, but then it would require a change in the method name.

Thanks for your work!

**Comment by chrischoy** [comment]
Please use the unabbreviated function `features_at_coordinates`.
