### ISSUE TITLE
Question for << ME.SparseTensorQuantizationMode.UNWEIGHTED_AVERAGE >>

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [NVIDIA/MinkowskiEngine#213]
Thanks for the wonderful engine.

I try my best to understand the engine and encounter some questions.

When I set my sparse tensor as 
`sparse_voxel_MinT = ME.SparseTensor(feats=sparse_voxel_feats_CUDA, coords=sparse_voxel_coords_CPU, quantization_mode=ME.SparseTensorQuantizationMode.UNWEIGHTED_AVERAGE)`

First, it does not work when feats.device is CUDA. 
If I replace 'sparse_voxel_feats_CUDA' with 'sparse_voxel_feats_CPU', it works.
The error message says " `*** RuntimeError: expected scalar type Int but found Long` "
Though I change the data type of the tensor, still it does not work for me.

Second, After I get `sparse_voxel_MinT` under the condition of `quantization_mode=ME.SparseTensorQuantizationMode.UNWEIGHTED_AVERAGE,` 
`sparse_voxel_MinT.requires_grad` is << False >> .
However, when I set `quantization_mode=ME.SparseTensorQuantizationMode.RANDOM_SUBSAMPLE`, 
`sparse_voxel_MinT.requires_grad` is << True >>.

I use image features as an input of the Minkowski engine but finally, back-propagation issues do matter.

If I could use `quantization_mode=ME.SparseTensorQuantizationMode.UNWEIGHTED_AVERAGE,`,
I guess the backward gradient properly spreads out through my image features that are overlapped within the single coordinate location.

Is there any solution that I can detour this issue?

**Comment by chrischoy** [comment]
The error `*** RuntimeError: expected scalar type Int but found Long` is for the coordinates. Use `.int()` to convert the long tensor to a int tensor.

Regarding the differentiable unweighted_average, I'll add to the v0.5 branch.

**Comment by chrischoy** [comment]
Updated v0.5 on https://github.com/NVIDIA/MinkowskiEngine/commit/45c09f156c02b2f661bcef2df516e40c3169e2f2
