### ISSUE TITLE
Unable to pickle Minkowski Layers

### ISSUE THREAD

**Issue by satabios** [NVIDIA/MinkowskiEngine#216]
I'm trying to save an model from the examples folder user using: `torch.save(net, 'test.pth')`. However, it throws an error stating `TypeError: can't pickle MinkowskiAvgPoolingFunction objects`

**Comment by chrischoy** [comment]
Please refer to the examples and use state_dict.

**Comment by satabios** [comment]
The reason I saved the whole model is to compare the model's size reduction . I also tried saving them using state_dict, however the size of the weights doubled and not halved. Is there a specific reason to this? Or did I miss any point in the paper.

**Comment by chrischoy** [comment]
Why would you use the pickle to compare model’s size? AveragePooling layer or any pooling layers don’t have any learnable parameters and pickling these layers is not the right way to compute model’s size.

You can simply compute the number of parameters with

```
np.sum([p.numel() for p in model.parameters()])
```

This is the number of parameters in a model.

**Comment by satabios** [comment]
I'm trying to convert this onto ONNX, is it possible to save the model?
