### ISSUE TITLE
fatal error: cuda_runtime_api.h:No such file or directory

### ISSUE THREAD

**Issue by yaoyishen** [NVIDIA/MinkowskiEngine#223]
I have run `conda install numpy mkl-include pytorch cudatoolkit=10.2 -c pytorch` successfuly. And `conda list` shows the packages are right.

But when I run `export CXX=gcc-7; python setup.py install`, some mistakes happend as follows!

Using BLAS=mkl
CXX src/region.cpp
CXX src/coordsmap.cpp
CXX src/pooling_max.cpp
CXX src/convolution_transpose.cpp
CXX src/convolution.cpp
CXX src/coords_manager.cpp
CXX src/union.cpp
CXX src/broadcast.cpp
CXX src/pruning.cpp
In file included from src/gpu_memory_manager.hpp:34:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/broadcast.cpp:25:
/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
In file included from src/gpu_memory_manager.hpp:34:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/convolution.cpp:25:
/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
In file included from src/gpu_memory_manager.hpp:34:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/convolution_transpose.cpp:25:
/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
In file included from src/gpu_memory_manager.hpp:34:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/coords_manager.cpp:25:
/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
In file included from src/gpu_memory_manager.hpp:34:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/pruning.hpp:28,
                 from src/pruning.cpp:25:
/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
In file included from src/gpu_memory_manager.hpp:34:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/pooling_max.cpp:25:
/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/gpu_memory_manager.hpp:34:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/union.hpp:28,
                 from src/union.cpp:25:
/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:162: recipe for target 'objs/pooling_max.o' failed
make: *** [objs/pooling_max.o] Error 1
Makefile:162: recipe for target 'objs/convolution_transpose.o' failed
make: *** [objs/convolution_transpose.o] Error 1
Makefile:162: recipe for target 'objs/convolution.o' failed
make: *** [objs/convolution.o] Error 1
Makefile:162: recipe for target 'objs/coords_manager.o' failed
make: *** [objs/coords_manager.o] Error 1
Makefile:162: recipe for target 'objs/broadcast.o' failed
make: *** [objs/broadcast.o] Error 1
Makefile:162: recipe for target 'objs/pruning.o' failed
make: *** [objs/pruning.o] Error 1
Makefile:162: recipe for target 'objs/union.o' failed
make: *** [objs/union.o] Error 1
Traceback (most recent call last):
  File "setup.py", line 188, in <module>
    run_command(*compile_args)
  File "setup.py", line 90, in run_command
    subprocess.check_call(args)
  File "/home/ncepucce/anaconda3/envs/3DMR/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-j8', 'PYTHON=/home/ncepucce/anaconda3/envs/3DMR/bin/python', 'BLAS=mkl')' returned non-zero exit status 2.

**Comment by xmyqsh** [comment]
cuda home cannot found by the following line in your side.
```
python3.6 -c 'from torch.utils.cpp_extension import _find_cuda_home; print(_find_cuda_home())'
```

In other word, your cuda home is not in the following path:

```
def _find_cuda_home():
    '''Finds the CUDA install path.'''
    # Guess #1
    cuda_home = os.environ.get('CUDA_HOME') or os.environ.get('CUDA_PATH')
    if cuda_home is None:
        # Guess #2
        try:
            which = 'where' if IS_WINDOWS else 'which'
            nvcc = subprocess.check_output(
                [which, 'nvcc']).decode().rstrip('\r\n')
            cuda_home = os.path.dirname(os.path.dirname(nvcc))
        except Exception:
            # Guess #3
            if IS_WINDOWS:
                cuda_homes = glob.glob(
                    'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v*.*')
                if len(cuda_homes) == 0:
                    cuda_home = '' 
                else:
                    cuda_home = cuda_homes[0]
            else:
                cuda_home = '/usr/local/cuda'
            if not os.path.exists(cuda_home):
                cuda_home = None 
    if cuda_home and not torch.cuda.is_available():
        print("No CUDA runtime is found, using CUDA_HOME='{}'".format(cuda_home))
    return cuda_home
```

**Comment by chrischoy** [comment]
It seems that pytorch fails to find the CUDA_HOME. Please provide the cuda home directory to the setup.py like the following.

```
python setup.py install --force_cuda --cuda_home=/usr/local/cuda
```

**Comment by yaoyishen** [comment]
> It seems that pytorch fails to find the CUDA_HOME. Please provide the cuda home directory to the setup.py like the following.
> 
> ```
> python setup.py install --force_cuda --cuda_home=/usr/local/cuda
> ```

The issue has been solved,thanks a lot!
