### ISSUE TITLE
RAM usage continuously increase when recursively feeding output to the input

### ISSUE THREAD

**Issue by alexzhou907** [NVIDIA/MinkowskiEngine#224]
I am modifying minkunet.py and concatenating a different new tensor to the input every training iteration. 

i.e. 
```
##Input: x, new_tensor
##Output: out

x_embed= x_embedding(x)
new_tensor_sparse = ME.SparseTensor(
            feats=new_tensor,
            coords=x_embed.coords,
            coords_key=x_embed.coords_key,
            coords_manager=x_embed.coords_man,
            force_creation=True
)

out = conv1(ME.cat(x_embed, new_tensor_sparse ))
out = conv2(...)
...
```
"out" here is recursively inputted back into the network and I observe that after conv1 CPU memory usage increases every time the recursion happens until CPU memory is used up. Is this caused by new hashmap being generated? How can I correctly concatenate a new tensor to existing tensors without using up memory? 

Notably, it would be desirable to clear existing hashmaps to release memory.

**Comment by xmyqsh** [comment]
@alexzhou907
Good catch! It is because of the overwrite of coords_key.
The bug will be fixed soon.

By the way, you can use remove `coords=x_embed.coords,` to prevent memory leak.
Like this:
```
x_embed= x_embedding(x)
new_tensor_sparse = ME.SparseTensor(
            feats=new_tensor,
            coords_key=x_embed.coords_key,
            coords_manager=x_embed.coords_man,
            force_creation=True
)
```

**Comment by alexzhou907** [comment]
Thanks for the reply. This didn't solve my issue. after conv1 memory still increases. Please note that I am inputting out back into the network I don't know if this plays into the issue.

**Comment by alexzhou907** [comment]
Since this is during evaluation, I worked around this problem by deleting computation graph and creating new x with features of output before inputting again into the network. The actual problem remains, however, so it would be helpful if this memory problem on recursive inputs can be addressed in the future. Thanks.

**Comment by chrischoy** [comment]
If you are feeding the output to the input, this will create a long chain of computation graph and pytorch cannot delete the computation graph. This will increase the RAM regardless of MinkowskiEngine.

If you want to break the dependency of the input from the previous output, consider using `.detach()`.

**Comment by rancheng** [comment]
@chrischoy  I recently run the customized model with multi-gpu, the memory leak happens.

here's the toy example of my customized model forward func (Adaptive Feature Fusion):

```python
        out_bnp3s1_att = ME.cat(out_b1p3s1_att, out_b2p3s1_att, out_b3p3s1_att)
        out_bnp3s1_att_sig = self.sigmoid(out_bnp3s1_att)
        out_bnp3s1_att_sig_sft = self.softmax(out_bnp3s1_att_sig)

        out_b1p3s1_att_rep = ME.SparseTensor(
            feats=out_bnp3s1_att_sig_sft.F[:, 0].view(-1, 1).repeat(1, out_b1p3s1.F.shape[1]).detach(),
            coords_manager=out_b1p3s1.coords_man,
            coords_key=out_b1p3s1.coords_key
        )
        out_b2p3s1_att_rep = ME.SparseTensor(
            feats=out_bnp3s1_att_sig_sft.F[:, 1].view(-1, 1).repeat(1, out_b2p2s1.F.shape[1]).detach(),
            coords_manager=out_b2p2s1.coords_man,
            coords_key=out_b2p2s1.coords_key
        )
        out_b3p3s1_att_rep = ME.SparseTensor(
            feats=out_bnp3s1_att_sig_sft.F[:, 2].view(-1, 1).repeat(1, out_b3p1s1.F.shape[1]).detach(),
            coords_manager=out_b3p1s1.coords_man,
            coords_key=out_b3p1s1.coords_key
        )
        # encoder block output
        out_b1p2 = out_b1p3s1 * out_b1p3s1_att_rep + out_b2p3s1_att_rep * out_b2p2s1 + out_b3p3s1_att_rep * out_b3p1s1
        # out_b1p2_cd = ME.SparseTensor(
        #     feats=out_b1p2.F,
        #     coords_manager=out_b2p2s1.coords_man,
        #     coords_key=out_b2p2s1.coords_key)

        # encoder stride 2 lvl:
        out_b1p2s2 = self.conv1p1s2_lv2(out_b1p2)
```

I'm not sure if it's because of new sparse tensor in forward function, since when I run single gpu, there's no memory leak at all.

**Comment by chrischoy** [comment]
You mean memory increase similar to https://discuss.pytorch.org/t/memory-usage-keeps-increasing-in-dataloader-in-very-simple-code/45103/1

This is not due to MinkowskiEngine.

**Comment by rancheng** [comment]
No I double checked with dataloader by simply comment out all the code after get the data from `next(train_loader)` the memory is constant.

However, once I include the code of these two lines:

```python
replicas = parallel.replicate(model, devices)
outputs = parallel.parallel_apply(replicas, inputs, devices=devices)
```

the memory leak happens.

**Comment by chrischoy** [comment]
I see. can you isolate the lines in the model that actually causes this issue by commenting out the unnecessary layers that does not cause this problem?

**Comment by rancheng** [comment]
I found a similar issue here: https://github.com/pytorch/pytorch/issues/46753
They suggest to try DistributedDataParallel, I'll give a shot tonight.

**Comment by thomas-enxuli** [comment]
@chrischoy 
I also have a similar issue when I use DataParallel with MinkowskiEngine where RAM usage continuously increases. Here's my toy example:
```python
for i in range(batches):
    inputs, all_labels = [], []
    for j in range(num_devices):
        coords, feats, labels = next(train_iter)
        with torch.cuda.device(devices[j]):
            inputs.append(ME.SparseTensor(feats.float(), coords).to(devices[j]))
        all_labels.append(labels.long().to(devices[j]))

    replicas = torch.nn.parallel.replicate(model, devices)
    outputs = torch.nn.parallel.parallel_apply(replicas, inputs, devices=devices)
```
This is coded following [https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu.py](https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu.py). CPU RAM usage keeps increasing each iteration even with the simplest model without back propagation. 
Here's the trivial model I tried
```python
class MinkUNetBase(ResNetBase):

    def __init__(self, in_channels, out_channels, D=3):
        ResNetBase.__init__(self, in_channels, out_channels, D)

    def network_initialization(self, in_channels, out_channels, D):
        self.inplanes = self.INIT_DIM
        self.conv0 = ME.MinkowskiConvolution( 
            in_channels, self.inplanes * 2, kernel_size=3, stride=1, dimension=D)
    def forward(self, x):
        return self.conv0(x)
```
If I comment out the last line `outputs = torch.nn.parallel.parallel_apply(replicas, inputs, devices=devices)`, then the RAM seems to be normal.

**Comment by chrischoy** [comment]
This seems to be a pytorch issue.
To confirm, can you use regular pytorch tensors and regular pytorch layers?

Also, please use the DistributedDataParallel instead of the DataParallel. I've have been using DDP with ME and have not encountered an issue.

**Comment by thomas-enxuli** [comment]
@chrischoy 
RAM issue is not present when I tried this training code using regular tensors and layers, but thanks for your reply. I will try DistributedDataParallel instead. Any chance of releasing an example with DistributedDataParallel just like https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu.py?

**Comment by chrischoy** [comment]
I recommend using pytorch-lightning for multi-gpu with MinkowskiEngine. You do not have to write any multi-gpu specific code to make MinkowskiEngine work for both single-gpu and multi-gpu using DDP.

**Comment by rancheng** [comment]
Turn out Distributed Data Parallel can work, I'll write a simple example and start a merge request later.

**Comment by chrischoy** [comment]
Multi gpu DDP example is available at https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu_ddp.py
Also, pytorch lightning example is available at
https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu_lightning.py

**Comment by Anurag14** [comment]
@chrischoy I am also facing similar issue, I am trying to rewrite the Pointgroup (https://github.com/dvlab-research/PointGroup) which is implemented in spconv to Minkowski Engine. 
```
class ResidualBlock(ME.MinkowskiNetwork):
    def __init__(self, in_channels, out_channels, norm_fn=None, D=3):
        super().__init__(D)

        if in_channels == out_channels:
            self.i_branch = nn.Sequential(
                nn.Identity()
            )
        else:
            self.i_branch = nn.Sequential(
                ME.MinkowskiConvolution(in_channels, out_channels, kernel_size=1, bias=False, dimension=D)
            )
        self.conv_branch = nn.Sequential(
            ME.MinkowskiBatchNorm(in_channels,eps=1e-4),
            ME.MinkowskiReLU(),
            ME.MinkowskiConvolution(in_channels, out_channels, kernel_size=3, bias=False, dimension=D),
            ME.MinkowskiBatchNorm(out_channels,eps=1e-4),
            ME.MinkowskiReLU(),
            ME.MinkowskiConvolution(out_channels, out_channels, kernel_size=3, bias=False, dimension=D)
            )

    def forward(self, input):
        #identity = ME.SparseTensor(features=input.features, coordinates=input.coordinates,coordinate_manager=input.coordinate_manager)
        output = self.conv_branch(input)
        output += self.i_branch(input)

        return output
class UNet(ME.MinkowskiNetwork):

    def __init__(self, nPlanes, block_reps, block, D=3):
        super(UNet, self).__init__(D)
        self.nPlanes = nPlanes
        self.block_layers = []
        self.encoder_layers = []
        self.decoder_layers = []
        self.block_tail_layers = []
        self.length_of_nplanes = len(nPlanes)
        for i in range(len(nPlanes)-1):
            blocks = [block(nPlanes[i], nPlanes[i], D) for j in range(block_reps)]
            blocks = nn.Sequential(*blocks)
            conv_block=nn.Sequential(
                    ME.MinkowskiBatchNorm(nPlanes[i]),
                    ME.MinkowskiReLU(),
                    ME.MinkowskiConvolution(
                        in_channels=nPlanes[i],
                        out_channels=nPlanes[i+1],
                        kernel_size=2,
                        dimension=D))
            self.block_layers.append(blocks)
            self.encoder_layers.append(conv_block)

            deconv_block=torch.nn.Sequential(
                        ME.MinkowskiBatchNorm(nPlanes[self.length_of_nplanes-i-1]),
                        ME.MinkowskiReLU(),
                        ME.MinkowskiConvolutionTranspose(
                        in_channels=nPlanes[self.length_of_nplanes-i-1],
                        out_channels=nPlanes[self.length_of_nplanes-i-2],
                        kernel_size=2,
                        dimension=D))
            blocks_tail = []
            for j in range(block_reps):
                blocks_tail.append(block(nPlanes[self.length_of_nplanes-i-2] * (2 - j), nPlanes[self.length_of_nplanes-i-2]))
            blocks_tail = torch.nn.Sequential(*blocks_tail)
            self.decoder_layers.append(deconv_block)
            self.block_tail_layers.append(blocks_tail)
            self.block_layers=nn.ModuleList(self.block_layers)
            self.encoder_layers=nn.ModuleList(self.encoder_layers)
            self.decoder_layers=nn.ModuleList(self.decoder_layers)
            self.block_tail_layers=nn.ModuleList(self.block_tail_layers)

    def forward(self, x):
        outputs = []
        for i in range(self.length_of_nplanes-1):
            x = self.block_layers[i](x)
            outputs.append(x.features)
            x = self.encoder_layers[i](x)

        for i in range(self.length_of_nplanes-1):
            x = self.decoder_layers[i](x)
            outputs[-1]=ME.SparseTensor(outputs[-1], coordinate_manager=x.coordinate_manager,coordinate_map_key=x.coordinate_map_key)
            u = ME.cat(x,outputs[-1])
            del outputs[-1]
            x = self.block_tail_layers[i](u)
        return x
```
The implementation constantly runs out of memory, whereas the parameters of the model as not that much and the original implementation runs with ~5GB space in GPU.
