### ISSUE TITLE
ImportError in v0.5

### ISSUE THREAD

**Issue by daihengming** [NVIDIA/MinkowskiEngine#227]
Hi Chris,
I've compiled ME v0.5 successfully with CUDA 10.2, Pytorch 1.5, GCC 7, Python 3.6
But when import ME in python I got an ImportError :undefined symbol: cusparseDestroyDnVec.

**Comment by chrischoy** [comment]
Hmm, it seems like the link might have not worked correctly. Can you install ME v0.4.3 and see if you can import correctly?

**Comment by daihengming** [comment]
Thanks for your reply.
I just installed ME v0.4.3 by using "python setup.py install" , and it can be imported without error.
And I do have 2 versions of cuda(cuda8.0 and cuda10.2) on my system, and I modify the Path in bashrc file to switch to the right version.

**Comment by chrischoy** [comment]
Could you run and see if you have cusparse in the correct path?

```
ls /usr/local/cuda-10.2/lib64/ | grep libcusparse.so
```

**Comment by daihengming** [comment]
I run the command and get the following results:
`nvcc --version`

> `nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
`

`ls /usr/local/cuda/lib64/ | grep libcusparse.so`

> libcusparse.so
libcusparse.so.10
libcusparse.so.10.3.1.89

Maybe the libcusparse version in the CUDA toolkit is not suitable?

**Comment by daihengming** [comment]
And I tried with cuda 10.1.243, but got the same import error.

**Comment by chrischoy** [comment]
Hmm I have the same setup for 10.2 with libcusparse.so.10.3.1.89.

Then the pytorch might not be using the correct CUDA_HOME

could you provide this explicitly?

```
export CUDA_HOME=/usr/local/cuda-10.2/; python setup.py install
```
