### ISSUE TITLE
Sparse tensor union operator in v0.5

### ISSUE THREAD

**Issue by murrdpirate** [NVIDIA/MinkowskiEngine#230]
When I try to get the union of two `SparseTensor`s via the `+` operator (after making them share `coordinate_manager`s), I get the following error:

`CoordinateManger has no attribute get_union_map`

It works fine in v0.4 (with slightly different syntax).

**Comment by chrischoy** [comment]
It works fine on https://github.com/NVIDIA/MinkowskiEngine/blob/master/tests/sparse_tensor.py#L142

**Comment by murrdpirate** [comment]
Hmm, I can see that both `SparseTensors` are using the global `CoordinateManager` in that case, but still when I perform the union, it tries to call `CoordinateManager.get_union_map`, which appears to be deprecated in `v0.5`. 

It shouldn't be calling `get_union_map` right? Maybe there's just something wrong with my installation.

**Comment by chrischoy** [comment]
Yes currently the union is not implemented on v0.5

**Comment by murrdpirate** [comment]
OK, good to know. Thanks!

**Comment by chrischoy** [comment]
Implemented on  fa88fa2434
