### ISSUE TITLE
Negative Coordinates Generation

### ISSUE THREAD

**Issue by zacjiang** [NVIDIA/MinkowskiEngine#232]
When I run MinkowskiConvolutionTranspose at (0, 0, 0), is there a way to make it generate negative coordinates?

**Comment by chrischoy** [comment]
Yes, it will generate new coordinates including negative coordinates if you provide the arguments to the layer to generate new coordinates.

**Comment by zacjiang** [comment]
Thanks, I misunderstood how different kernel sizes affect the results.
