### ISSUE TITLE
module 'MinkowskiEngineBackend._C' has no attribute 'quantize_label_np'

### ISSUE THREAD

**Issue by chronbird** [NVIDIA/MinkowskiEngine#233]
Hi Chris,

When I use the function sparse_quantize in v0.5, I find the following error:
`module 'MinkowskiEngineBackend._C' has no attribute 'quantize_label_np'`

What I run is the segmentation model from your repo https://github.com/chrischoy/SpatioTemporalSegmentation, and I tried to change it to Minkowskiv0.5 version. The error occurs in voxelizer.py:
`coords_aug, feats, labels = ME.utils.sparse_quantize(
                coords_aug, feats, labels=labels, ignore_label=self.ignore_label)`

I wonder if I installed the Minkowski wrongly, how I installed was to first create a new conda environment, and then install pytorch1.6 by conda command. The Minkowskiv0.5 was installed by the command provided in this repo README.

Could you help me with error? thanks.

================================================================================

Update:

I find the quantize function in MinkowskiEngine/utils/quantization.py can return a unique_map and a inverse_map. For segmentation task, is it ok to just use this function to get the unique_map and drop those labels not associated with unique_map?

==================================================================================
Update 1/10/2020:

The above work-around seems working but the performance drops significantly compared to v0.4. I found that the `quantize_label_np` function can assign some labels to be ignored, while the `quantize` function cannot do this. Another thing is the RegionType.HYBRID in v0.4 disappeared in v0.5. I am not sure whether these differences cause the issue. Can you kindly advise how to make quantize_label_np work? 

==================================================================================
Update 4/10/2020:
I saw the function `quantize_label_np` and `quantize_label_th` are commented in the file pybind/extern.hpp and src/quantization.cpp, are they deprecated?

**Comment by chrischoy** [comment]
The quantization function `sparse_quantize` has been updated on https://github.com/NVIDIA/MinkowskiEngine/commit/350672ab4004303b6f50e028fbe32cf6a4b4caf1 and do not use `quantize_label_np` or `quantize_label_th`.

**Comment by wu-zhonghua** [comment]
> I found that the `quantize_label_np` function can assign some labels to be ignored

Hi chronbird,

I also have a question about this. I find that the **quantize_label_np** function can assign some labels to be ignored. I would like to know in which situation, they will assign the label to be ignored. Thank you.

Regards
