### ISSUE TITLE
create_coords_key in v0.5

### ISSUE THREAD

**Issue by zacjiang** [NVIDIA/MinkowskiEngine#237]
Hi, I noticed that coordinate_manager.create_coords_key has been removed in v0.5. Is there a way to still achieve this? Thanks!

**Comment by zacjiang** [comment]
Also the get_kernel_map method:
https://github.com/NVIDIA/MinkowskiEngine/blob/0dfb30b66d6405486a61090e79f799838d5e0822/MinkowskiEngine/MinkowskiCoordinateManager.py#L315-L327

**Comment by chrischoy** [comment]
The create_coords_key was replaced with `insert_and_map`. The get kernel map function is currently under development and will be available soon.

**Comment by zacjiang** [comment]
Great, thanks!
