### ISSUE TITLE
GlobalPooling requiring a mode in v0.50

### ISSUE THREAD

**Issue by aniqueakhtar** [NVIDIA/MinkowskiEngine#238]
Just tried v0.50, got this error:
```
self.pooling = ME.MinkowskiGlobalPooling()
TypeError: __init__() missing 1 required positional argument: 'mode'
```

**Comment by aniqueakhtar** [comment]
Probably missing
`PoolingMode.AUTO`
on line 669 in this file:
https://github.com/NVIDIA/MinkowskiEngine/blob/v0.5/MinkowskiEngine/MinkowskiPooling.py

**Comment by aniqueakhtar** [comment]
Had to resort to using:
```
self.pooling = ME.MinkowskiGlobalMaxPooling()
```

**Comment by chrischoy** [comment]
provided default arg on 8374156d7da14d6f6b30f8f083a9462e300a1281
