### ISSUE TITLE
0.50 error: 'MinkowskiEngineBackend._C.CoordinateMapKey' object has no attribute 'set_tensor_stride'

### ISSUE THREAD

**Issue by aniqueakhtar** [NVIDIA/MinkowskiEngine#241]
```
out.tensor_stride = [2]*3

  File "/home/anique/anaconda3/envs/mink2/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiTensor.py", line 358, in tensor_stride
    self.coordinate_map_key.set_tensor_stride(p)
AttributeError: 'MinkowskiEngineBackend._C.CoordinateMapKey' object has no attribute 'set_tensor_stride'
```

Whenever I manually assign a stride using `tensor_stride`, I get this error

**Comment by chrischoy** [comment]
The modification of the tensor stride does not propagate to the coordinate manager. Thus, I had to prevent this to prevent unpredictable behaviors on 289e9a38e9f53a5407fa28f8524bae835a94e002.

Instead, when you create a sparse tensor, provide the tensor stride as a keword argument.
