### ISSUE TITLE
Installing v0.5 in docker/singularity

### ISSUE THREAD

**Issue by edraizen** [NVIDIA/MinkowskiEngine#243]
Hello, I am trying to migrate v0.5, but am having difficulty installing inside of a Singularity container. The nvidia drivers are installed in the base image (nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04) and pytorch installed via conda.

When I install ME v0.5 with --force_cuda and --cuda_home, it gives me the error:
```
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```
full error here: https://gist.github.com/edraizen/01f8ea9932c098c131b4ddb844a44974

I am building it on an aws ec2 instance with and without a gpu and they both fail.

Any help would be appreciated, thanks!

**Comment by rsdmse** [comment]
I'm having the same problem in Docker on MacOS. I didn't encounter this issue in v0.4.

**Comment by rsdmse** [comment]
Seems related to #135

**Comment by edraizen** [comment]
I found out that TORCH_CUDA_ARCH_LIST has to be set: e.g. `export TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1"`
