### ISSUE TITLE
 0.5: module 'MinkowskiEngine' has no attribute 'MinkowskiPoolingTranspose'

### ISSUE THREAD

**Issue by fengziyue** [NVIDIA/MinkowskiEngine#250]
`model = nn.Sequential(
                ME.MinkowskiPoolingTranspose(2, 2, dimension=3),
                ME.MinkowskiConvolution(
                    in_channels=num_ch_in,
                    out_channels=num_ch_out,
                    kernel_size=3,
                    stride=1,
                    dilation=1,
                    bias=False,
                    dimension=3),
                ME.MinkowskiBatchNorm(num_ch_out),
                ME.MinkowskiReLU())`

`ME.MinkowskiPoolingTranspose(2, 2, dimension=3),
AttributeError: module 'MinkowskiEngine' has no attribute 'MinkowskiPoolingTranspose'`

Version:0.5
Ubuntu18.04
CUDA10.2

**Comment by fengziyue** [comment]
@chrischoy

**Comment by fengziyue** [comment]
Seems V0.5 doesn't have the PoolingTranspose, maybe I have to use ConvolutionTranspose, is that correct?

**Comment by chrischoy** [comment]
Right, it will be added in the future. At the moment, please use the conv tr.

**Comment by chrischoy** [comment]
Let me reopen, just to keep track of the progress.

**Comment by chrischoy** [comment]
Implemented on https://github.com/NVIDIA/MinkowskiEngine/commit/d0614b6b450937710aab2c82a2dae21ce95dd57f
