### ISSUE TITLE
Training terminates after pruning generates an empty SparseTensor

### ISSUE THREAD

**Issue by khakhlyuk** [NVIDIA/MinkowskiEngine#252]
Hello, I get the following error when running the completion example:

```
src/pruning.cpp:110, (true) MinkowskiPruning: Generating an empty SparseTensor
terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
```

I am using ME 0.4.3, jupyter notebooks, pytorch 1.6.0, cuda toolkit 10.1.243.

**Comment by chrischoy** [comment]
When using MinkowskiPruning, make sure your keep vector has at least one `True`. Otherwise, this will raise a runtime error.

```python
pruning = ME.MinkowskiPruning()
if keep.sum() > 0:
    stensor = pruning(stensor, keep)
else:
    break  # stop the network forward from now on since an empty tensor is generated.
```

**Comment by khakhlyuk** [comment]
This helped indeed! Should have guessed myself, probably :) 
Thank you very much for such a quick response!
