### ISSUE TITLE
Is there any way to calculate the model size, like torchsummary?

### ISSUE THREAD

**Issue by somebodyus** [NVIDIA/MinkowskiEngine#254]
I am wondering if there Is any way to calculate the model size.
For normal pytorch code, we can use torchsummary. But Minkowski cannot use torchsummary.

**Comment by satabios** [comment]
The documentation clearly states that the weights of the model can be save. A similar issue has already been discussed at [https://github.com/NVIDIA/MinkowskiEngine/issues/216](url)

**Comment by somebodyus** [comment]
> The documentation clearly states that the weights of the model can be save. A similar issue has already been discussed at [https://github.com/NVIDIA/MinkowskiEngine/issues/216](url)

cannot open this link

**Comment by satabios** [comment]
My mistake, it can be found here: [https://github.com/NVIDIA/MinkowskiEngine/issues/216#issuecomment-698133850](url)
