### ISSUE TITLE
After sparse quantization, does one voxel only contain one point?

### ISSUE THREAD

**Issue by somebodyus** [NVIDIA/MinkowskiEngine#260]
After sparse quantization, does one voxel only contain one point? How to select a point in a voxel? 
Could anyone give me some details on the sparse quantization? The code on quantize is written in C++, which is difficult to understand.

**Comment by chrischoy** [comment]
Yes, it is guaranteed to have only one unique coordinate per voxel.

**Comment by somebodyus** [comment]
> Yes, it is guaranteed to have only one unique coordinate per voxel. Currently, it is using the coordinate map (hash table) to select one point that it finds first in the coordinate matrix and ignores all points that are quantized to the same coordinate. The GPU version uses different way to select unique coordinates and it is pseudo random.

Thank you so much.
