### ISSUE TITLE
Installing the setup file

### ISSUE THREAD

**Issue by janardhan08** [NVIDIA/MinkowskiEngine#261]
When I am installing the setup file I get this error, i would really appreciate the help 

 
Using BLAS=openblas
CXX src/region.cpp
CXX src/coordsmap.cpp
CXX src/convolution_transpose.cpp
CXX src/pooling_global_max.cpp
CXX src/pooling_transpose.cpp
CXX src/union.cpp
CXX src/coords_manager.cpp
CXX src/broadcast.cpp
CXX src/math_functions.cpp
CXX src/pruning.cpp
CXX src/pooling_global_avg.cpp
CXX src/pooling_avg.cpp
CXX src/quantization.cpp
CXX src/coords_key.cpp
CXX src/pooling_max.cpp
CXX src/convolution.cpp
NVCC src/pooling_max.cu
nvcc fatal   : Value 'c++14' is not defined for option 'std'
Makefile:166: recipe for target 'objs/cuda/pooling_max.o' failed
make: *** [objs/cuda/pooling_max.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
Traceback (most recent call last):
  File "setup.py", line 188, in <module>
    run_command(*compile_args)
  File "setup.py", line 90, in run_command
    subprocess.check_call(args)
  File "/Data4T/janardhan/anaconda3/envs/dlv/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-j12', 'PYTHON=/Data4T/janardhan/anaconda3/envs/dlv/bin/python', 'BLAS=openblas')' returned non-zero exit status 2.

**Comment by As-Time-Goes-By** [comment]
@janardhan08 
I meet the same problem, can you tell me your solution?
Thanks!

**Comment by janardhan08** [comment]
There was some dependency issue in my earlier due to which it didnot work. I created a new environment and installed it again. it worked. 
Also make sure you have correct cuda or C++ version installed.

**Comment by As-Time-Goes-By** [comment]
> There was some dependency issue in my earlier due to which it didnot work. I created a new environment and installed it again. it worked. Also make sure you have correct cuda or C++ version installed.

Can you show your  environment configurations?
Thanks！

**Comment by janardhan08** [comment]
Currently, I don’t have the access to the system which I built it on.
