### ISSUE TITLE
Possible typo in Makefile

### ISSUE THREAD

**Issue by liu115** [NVIDIA/MinkowskiEngine#262]
https://github.com/NVIDIA/MinkowskiEngine/blob/21f3930d8bb7d27e844b21aeaf7c1a444576d853/Makefile#L64

I wonder the `./` in `./ $(CUDA_HOME)/include` is a typo. Thank you.

**Comment by chrischoy** [comment]
Its not a typo. It adds the current folder for the include files. Regardless, I deprecated the Makefile in v0.5.
