### ISSUE TITLE
0.5 parallel.replicate cannot replicate dimension attribute for convolution

### ISSUE THREAD

**Issue by lshiwjx** [NVIDIA/MinkowskiEngine#264]
When using multiple-GPU training in v5 as :
`models = parallel.replicate(model, devices)`

get errors 
`torch.nn.modules.module.ModuleAttributeError: 'MinkowskiConvolution' object has no attribute 'dimension'`

I found that many attributes are not corrected replicated.

**Comment by chrischoy** [comment]
Try to use distributed data parallel.

I also recommend using pytorch lightning instead of writing DDP manually which is prone to errors.

**Comment by lshiwjx** [comment]
Thanks very much. 

Are there any examples? The official multiple-GPU examples recommend the "parallel" way as in [here](https://nvidia.github.io/MinkowskiEngine/demo/multigpu.html)

**Comment by chrischoy** [comment]
Please refer to the multi-gpu DDP on https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu_ddp.py
