### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Xinghui-Li** [NVIDIA/MinkowskiEngine#266]
I use Anaconda to install all dependencies. I have tried running both
`python setup.py install --blas=mkl`
AND
`python setup.py install --blas=mkl`
BUT I kept getting the same error:
_g++ -pthread -shared -B /home/xinghui/miniconda3/envs/mink/compiler_compat -L/home/xinghui/miniconda3/envs/mink/lib -Wl,-rpath=/home/xinghui/miniconda3/envs/mink/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/xinghui/Academic/MinkowskiEngine/build/temp.linux-x86_64-3.7/pybind/minkowski.o -Lobjs -L/home/xinghui/miniconda3/envs/mink/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda-10.2/lib64 -lminkowski -lcusparse -lmkl -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so
/home/xinghui/miniconda3/envs/mink/compiler_compat/ld: cannot find -lmkl
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1_
There are some warning during the installation:
/home/xinghui/miniconda3/envs/mink/lib/python3.7/site-packages/torch/include/c10/util/TypeCast.h(39): warning: calling a _constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during:
            instantiation of "dest_t c10::static_cast_with_inter_type<dest_t, src_t>::apply(src_t) [with dest_t=c10::complex<double>, src_t=double]" 
(166): here
            instantiation of "To c10::convert<To,From>(From) [with To=c10::complex<double>, From=double]" 
(178): here
            instantiation of "To c10::checked_convert<To,From>(From, const char *) [with To=c10::complex<double>, From=double]" 
/home/xinghui/miniconda3/envs/mink/lib/python3.7/site-packages/torch/include/c10/core/Scalar.h(66): here_
My environment is
Pytorch=1.6
gcc=7.5.0
CUDA=10.2.89

**Comment by chrischoy** [comment]
```
/home/xinghui/miniconda3/envs/mink/compiler_compat/ld: cannot find -lmkl
collect2: error: ld returned 1 exit status
```

Follow the instruction to install mkl.

https://github.com/NVIDIA/MinkowskiEngine#1-create-a-conda-virtual-environment-and-install-requirements

**Comment by Xinghui-Li** [comment]
I indeed have installed mkl. 

![image](https://user-images.githubusercontent.com/32851058/99947367-dcfe1600-2db2-11eb-9bc2-b3d9c242d4cc.png)

**Comment by chrischoy** [comment]
Can you try blas

```
sudo apt install libopenblas-dev
python setup.py install
```

**Comment by Xinghui-Li** [comment]
Yes, it is working. Thanks
