### ISSUE TITLE
CoordinateMapKey collision detected: (1 1 1, )

### ISSUE THREAD

**Issue by zhulf0804** [NVIDIA/MinkowskiEngine#272]
How to solve the following error?

/root/code/MinkowskiEngine/src/coordinate_map_manager.cpp:316, (true) CoordinateMapKey collision detected: (1 1 1, ) generating new string id

The part code is as following:

```
def sparse_input(xyzs, feats, voxel_size):
    batch_coords, batch_feats = [], []
    for i in range(xyzs.shape[0]):
        xyz, feat = xyzs[i], feats[i]
        coord = xyz / voxel_size
        batch_feats.append(feat)
        batch_coords.append(coord)
    batch_coords = ME.utils.batched_coordinates(batch_coords).cuda()
    input = ME.SparseTensor(torch.cat(batch_feats, dim=0),
                            coordinates=batch_coords,
                            quantization_mode=ME.SparseTensorQuantizationMode.UNWEIGHTED_AVERAGE)
    return input

src_input = sparse_input(xyz_src_t, norm_src_t,
                                               voxel_size=self.voxel_size)
feat_src = self.feat_extractor(src_input)
feat_src = feat_src.slice(src_input)
```

**Comment by chrischoy** [comment]
This is a warning, not an error. It says that a coordinate map exists for the tensor stride (1, 1, 1) so it will add random string to make a unique coordinate map key.

**Comment by zhulf0804** [comment]
Thanks @chrischoy ,
but when training, it will output pieces of warning message. 
In my opinion, maybe commenting on this line of code is a good choice.

**Comment by chrischoy** [comment]
Got it. Will be converted to a debugging output not a warning.
