### ISSUE TITLE
Error report "RuntimeError: CUSPARSE_STATUS_INVALID_VALUE at..." when using MinkowskiSumPooling in v0.5

### ISSUE THREAD

**Issue by dante0shy** [NVIDIA/MinkowskiEngine#281]
Hi Choy,

I'm working on a function that requires to check whether there is any nearest neighbor in point cloud **A** at the coordinates in point cloud **B**. My way is to use a  sum pooling like below.
```
com_sum = ME.MinkowskiSumPooling(kernel_size=5, dimension=D,)
com_index = torch.abs(com_sum(PC_a, coordinates=PC_b.C).F).sum(1) > 0
```
com_index would be the index that those points in PC_b have any nearest neighbor in PC_a. When I use this code, the error `RuntimeError: CUSPARSE_STATUS_INVALID_VALUE at...` shows up randomly, but when I change my code as below, this error just disappears.
```
com_max = ME.MinkowskiMaxPooling(kernel_size=5, dimension=D,)
com_index = torch.abs(com_max (PC_a, coordinates=PC_b.C).F).sum(1) > 0
```
I only change the sum pooling to max pooling, so I think there might be some bugs for MinkowskiSumPooling. Furthermore, I know it might not be the best way to realize my function, and is there any direct way to realize my function?

Thank you for your time!

**Comment by chrischoy** [comment]
Could you post, CUDA version, nvidia driver version?

**Comment by dante0shy** [comment]
Sure. My working environment is as following:
```
CUDA: 11.1
Nvidia driver: 455.45.01
Python: 3.7
Pytorch: 1.7
```
I directly compile and install the package with the branch v0.5 instead of `pip install git+https://github.com/NVIDIA/MinkowskiEngine.git@v0.5` .

**Comment by chrischoy** [comment]
Please install from the master

```bash
pip install git+https://github.com/NVIDIA/MinkowskiEngine.git
```
