### ISSUE TITLE
type object 'MinkowskiEngineBackend._C.RegionType' has no attribute 'HYPERCUBE'

### ISSUE THREAD

**Issue by poodarchu** [NVIDIA/MinkowskiEngine#284]
v0.5.0

**Comment by chrischoy** [comment]
Can you please put minimally reproducible code?

**Comment by poodarchu** [comment]
https://github.com/facebookresearch/PointContrast/blob/master/pretrain/pointcontrast/model/res16unet.py#L47

**Comment by chrischoy** [comment]
Please make sure you installed correctly.

**Comment by gaojunjie1234** [comment]
I have a same question, have you solved this problem?

run demo.py
Q:AttributeError: type object 'MinkowskiEngineBackend._C.RegionType' has no attribute 'HYPERCUBE'  │
    print(ME.__version__)   0.5.0c

**Comment by chrischoy** [comment]
Ah sorry,

This is due to the name change

Please use `HYPER_CUBE` instead of `HYPERCUBE`.

**Comment by RyanRuihanG** [comment]
Hello! ME.RegionType.HYBRID in v0.4.3 disappears in v0.5. I wonder what's the replacement.

**Comment by ruben-sethi** [comment]
It seems like `RegionType.HYBRID` disappeared with some refactoring of the enum in v0.5, and in `MinkowskyKernelGenerator.py`, there is also some inconsistent references to `RegionType.HYBRID` residual from this commit: https://github.com/NVIDIA/MinkowskiEngine/commit/8633896e5531ede729ab5f920c43309a4d59a28f

specifically, the code here is commented out https://github.com/NVIDIA/MinkowskiEngine/blob/master/MinkowskiEngine/MinkowskiKernelGenerator.py#L66 and the code here is not https://github.com/NVIDIA/MinkowskiEngine/blob/master/MinkowskiEngine/MinkowskiKernelGenerator.py#L152

**Comment by sandeepnmenon** [comment]
Is the RegionType.HYBRID issue fixed in any version?
I am getting error for the SpatioTemporalSegmentation code. I replaced HYPERCUBE and HYPERCROSS with the "_" version.
 
  File "/home/deepenai/SandeepMenon/SpatioTemporalSegmentation/main.py", line 28, in <module>
    from models import load_model, load_wrapper
  File "/home/SandeepMenon/SpatioTemporalSegmentation/models/__init__.py", line 1, in <module>
    import models.resunet as resunet
  File "/home/SandeepMenon/SpatioTemporalSegmentation/models/resunet.py", line 1, in <module>
    from models.resnet import ResNetBase, get_norm
  File "/home/SandeepMenon/SpatioTemporalSegmentation/models/resnet.py", line 6, in <module>
    from models.modules.common import ConvType, NormType, get_norm, conv, sum_pool
  File "/home/SandeepMenon/SpatioTemporalSegmentation/models/modules/common.py", line 58, in <module>
    ConvType.SPATIAL_HYPERCUBE_TEMPORAL_HYPERCROSS: ME.RegionType.HYBRID
AttributeError: type object 'MinkowskiEngineBackend._C.RegionType' has no attribute 'HYBRID'

What to do for the HYBRID enum ?

**Comment by HrbustLSH** [comment]
> Is the RegionType.HYBRID issue fixed in any version? I am getting error for the SpatioTemporalSegmentation code. I replaced HYPERCUBE and HYPERCROSS with the "_" version.
> 
> File "/home/deepenai/SandeepMenon/SpatioTemporalSegmentation/main.py", line 28, in from models import load_model, load_wrapper File "/home/SandeepMenon/SpatioTemporalSegmentation/models/**init**.py", line 1, in import models.resunet as resunet File "/home/SandeepMenon/SpatioTemporalSegmentation/models/resunet.py", line 1, in from models.resnet import ResNetBase, get_norm File "/home/SandeepMenon/SpatioTemporalSegmentation/models/resnet.py", line 6, in from models.modules.common import ConvType, NormType, get_norm, conv, sum_pool File "/home/SandeepMenon/SpatioTemporalSegmentation/models/modules/common.py", line 58, in ConvType.SPATIAL_HYPERCUBE_TEMPORAL_HYPERCROSS: ME.RegionType.HYBRID AttributeError: type object 'MinkowskiEngineBackend._C.RegionType' has no attribute 'HYBRID'
> 
> What to do for the HYBRID enum ?

Same question here .Did you solve it ?

**Comment by robertod** [comment]
I haven't personally tested it, but I have seen `HYBRID` in [the original implementation](https://github.com/chrischoy/SpatioTemporalSegmentation/blob/4afee296ebe387d9a06fc1b168c4af212a2b4804/models/modules/common.py#L58) replaced with `HYPER_CUBE` in [Mask3D](https://github.com/JonasSchult/Mask3D/blob/11bd5ff94477ff7194e9a7c52e9fae54d73ac3b5/models/modules/common.py#L69).
