### ISSUE TITLE
Is ME.utils.sparse_quantize() differentiable?

### ISSUE THREAD

**Issue by XLechter** [NVIDIA/MinkowskiEngine#287]
Hi, thanks for your great work first.

I have the following question:

I use a generator network (such as PointNet) to generate point clouds named **pc** which are **(n_clouds, num_points, channels)** tensor, and then convert it to the sparse tensor with the following codes:

**coords = ME.utils.sparse_quantize(coords=pc,quantization_size=params.model_params.mink_quantization_size)
bcoords = ME.utils.batched_coordinates([coords])**

and then use MinkowskiEngine to processe the sparse tensor (such as for classification).

so I wonder if the gradients can back-propagate to the former generator network if I train the whole network end-to-end?

Thank you!

**Comment by chrischoy** [comment]
Assuming the points are already batched, `ME.TensorField.sparse` provides a differentiable way to generate a sparse tensor.

For more, please refer to
https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/indoor.py#L133

**Comment by XLechter** [comment]
@chrischoy Thanks so much for your reply.
I check the link and find the **coords** to be numpy array on cpu and the **features** to be tensors on gpu. 
If I use a PointNet alike architecture to generate the point cloud **coords**, and set each point-wise feature to be 1 tensors. Does this mean only the feature tensors can be changed when the whole network update, and the coords can not be updated? 
Thanks.

**Comment by chrischoy** [comment]
Only the features can pass gradients.

**Comment by XLechter** [comment]
@chrischoy Thank you for replying.
