### ISSUE TITLE
Attention mechanism with MinkowskiEngine 

### ISSUE THREAD

**Issue by qiaozhijian** [NVIDIA/MinkowskiEngine#289]
Hello. Can we implement attention mechanism such as SE-Net and Transformer with MinkowskiEngine ?

**Comment by chrischoy** [comment]
The SEBlock is implemented on https://github.com/NVIDIA/MinkowskiEngine/blob/master/MinkowskiEngine/modules/senet_block.py#L50.

The transfomers can be implemented by extending this layer, but this could be a good addition to the library.

**Comment by qiaozhijian** [comment]
@chrischoy  Thank you very much! Salute！

**Comment by jaswanthbjk** [comment]
@qiaozhijian Did you manage to create one already ?

**Comment by qiaozhijian** [comment]
> @qiaozhijian Did you manage to create one already ?

No, I didn't.
