### ISSUE TITLE
ME.CoordinateManager.get_row_indices_per_batch

### ISSUE THREAD

**Issue by chrockey** [NVIDIA/MinkowskiEngine#295]
**Is your feature request related to a problem? Please describe.**
In MEv0.5.0, CoordinateManager does not have "get_row_indices_per_batch" method, which was available in MEv.0.4.3.

**Describe the solution you'd like**
The same function as "get_row_indices_per_bath" in MEv0.4.3

**Describe alternatives you've considered**
Currently, I implement a similar function using torch.where(stensor.C[:, 0] == batch_idx) but this is not elegant :(.

**Additional context**

**Comment by chrischoy** [comment]
Please refer to https://github.com/NVIDIA/MinkowskiEngine/blob/a83f2db29ee30a1fa9aaf2b839402bbdfcb22119/MinkowskiEngine/MinkowskiTensor.py#L271

**Comment by chrockey** [comment]
Oh, I was not aware of that function.
Thank you!

**Comment by wanghangege** [comment]
> Oh, I was not aware of that function. Thank you!

sorry.I still do not know how to replace function "get_row_indices_per_batch", could you help me in:
**             row_indices_per_batch = out.coords_man.get_row_indices_per_batch(out.coords_key)
**
tks.

**Comment by zhren711** [comment]
> > Oh, I was not aware of that function. Thank you!
> 
> sorry.I still do not know how to replace function "get_row_indices_per_batch", could you help me in: ** row_indices_per_batch = out.coords_man.get_row_indices_per_batch(out.coords_key) ** tks.

HELLO! I also met this problem ,have you solved this?
