### ISSUE TITLE
[Question] Why the completion example uses ELU instead of ReLU?

### ISSUE THREAD

**Issue by chrockey** [NVIDIA/MinkowskiEngine#297]
Hi,

I have a brief question about the completion example.
Why the CompletionNetwork uses ELU activation function instead of ReLU?
Is there any specific reason to use ELU instead of ReLU?

Thanks!

**Comment by chrischoy** [comment]
Not exactly. I just thought it might make people look into other activations.

**Comment by chrockey** [comment]
Thank you for your kind reply!
