### ISSUE TITLE
4D Tensor Convolution

### ISSUE THREAD

**Issue by theycallmefm** [NVIDIA/MinkowskiEngine#298]
Hi,  I want to apply convolution through a 4D tensor but I couldn't find any example regarding this. There may be something wrong about my intuition. 

**Inputs:**    coordinates size of [B,1024,3] and features size of [B, 1024, 6, 16].
**Goal:** If I would have applied a regular dense convolution I would have wanted to achieve feature size of  [B, 1024, 64, 16] and afterwards I would get maximum values on dimension 3. In the end I want to achieve features size of [B,1024,64]. 

How can I achieve this using Minkowski Convolutions? If I change size of my input feature tensor, let's say [B,1024, 96], will it be the right way? Because as I understand you can only use matrices as features on sparse tensor creation. I don't know how can I create a sparse tensor using 3 dimensional features.

**Comment by chrischoy** [comment]
The input should be a sparse tensor, not a dense tensor.

Please read the 4D Spatio-Temporal ConvNets, Minkowski ConvNets, CVPR'19, Fully Convolutional Geometric Features, ICCV'19 to to understand how it should be correctly defined.
