### ISSUE TITLE
[Question] Does TransposedConvolution work when kernel_size > stride?

### ISSUE THREAD

**Issue by chrockey** [NVIDIA/MinkowskiEngine#301]
Hi,

I noticed that there is a TODO mark in ME.MinkowskiTransposedConvolution.
https://github.com/NVIDIA/MinkowskiEngine/blob/b943600e69595e11c9102de1dc287afabdab5de9/MinkowskiEngine/MinkowskiConvolution.py#L511
However, it seems to work fine when I tested it for the case that kernel size is 3 and stride is 2.
Does it support 'kernel_size > stride' currently?

Thanks!

Regards,

Chunghyun Park

**Comment by chrischoy** [comment]
Ah, that should be removed. Thanks for noticing this.
