### ISSUE TITLE
Create layer with ME.RegionType.CUSTOM 

### ISSUE THREAD

**Issue by dragonlong** [NVIDIA/MinkowskiEngine#303]
Hi Chris, 

Thanks for keep updating this library. I tried to run the **Synthia 4D** experiment based on ME v0.5 pn a remote CentOS server. Everything works well, except that when I try to create a `ConvType.SPATIAL_HYPERCUBE_TEMPORAL_HYPERCROSS` convolution layer, which will be mapped to `ME.RegionType.CUSTOM` automatically. But it seems *region_offsets*  is not generated in the [convert_conv_type()](https://github.com/chrischoy/SpatioTemporalSegmentation/blob/5af74cbc57c8c431851223963886d39f724e4b14/models/modules/common.py#L110)  function, which is needed by `ME.KernelGenerator()` . A naive NxD list doesn't seem to work here. If it doesn't bother too much, may I know what would be a quick fix to that? I noticed that it seems to be similar to HYBRID in previous versions. 

Thanks!

Best,
Xiaolong

**Comment by dragonlong** [comment]
Just a follow-up, I am able to use 'ConvType.SPATIO_TEMPORAL_HYPERCROSS' or 'ConvType.SPATIO_TEMPORAL_HYPERCUBE', the training seems to go well. So I will close this issue report now. Thanks!

**Comment by sandeepnmenon** [comment]
+1
I have the same issue with 0.5.x version of ME. Not sure how to map `ConvType.SPATIAL_HYPERCUBE_TEMPORAL_HYPERCROSS` with `ME.RegionType.CUSTOM`

@dragonlong Where you able to reproduce the results by replacing this with 'ConvType.SPATIO_TEMPORAL_HYPERCROSS' or 'ConvType.SPATIO_TEMPORAL_HYPERCUBE' ?
Did you change the CONV_TYPE for [STRes16UNetBase](https://github.com/chrischoy/SpatioTemporalSegmentation/blob/5af74cbc57c8c431851223963886d39f724e4b14/models/res16unet.py#L336) ?
