### ISSUE TITLE
Is it possible to provide a conda list of a virtual environment where the package can be installed succesfully?

### ISSUE THREAD

**Issue by wzm2256** [NVIDIA/MinkowskiEngine#307]
**Is your feature request related to a problem? Please describe.**
I have been trying to install the package in every possible way during the past few days.
Still, I can not install the package due to all sorts of different errors, including dependence conflict, compile error.

**Describe the solution you'd like**
A conda package list of all required dependence. This can be done by 
``
conda list
``
in the target environment.

**Describe alternatives you've considered**
It is also possible to clarify the version of every required package in the readme file.
For example
``
conda install pytorch=1.5 cudatoolkit=10.1 -c pytorch
``
instead of 
``
conda install pytorch -c pytorch
``

**Additional context**

**Comment by wzm2256** [comment]
I have successfully installed this package, and I share my environment here.

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2021.1.19            h06a4308_0    defaults
certifi                   2020.12.5        py38h06a4308_0    defaults
cudatoolkit               10.2.89              hfd86e86_1    defaults
freetype                  2.10.4               h5ab3b9f_0    defaults
intel-openmp              2020.2                      254    defaults
jpeg                      9b                   h024ee3a_2    defaults
lcms2                     2.11                 h396b838_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
libuv                     1.40.0               h7b6447c_0    defaults
lz4-c                     1.9.3                h2531618_0    defaults
minkowskiengine           0.5.0                    pypi_0    pypi
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py38he904b0f_0    defaults
mkl_fft                   1.2.0            py38h23d657b_0    defaults
mkl_random                1.1.1            py38h0573a6f_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.10.2           py38hff7bd54_0    defaults
numpy                     1.19.2           py38h54aff64_0    defaults
numpy-base                1.19.2           py38hfa32c7d_0    defaults
olefile                   0.46                       py_0    defaults
openssl                   1.1.1i               h27cfd23_0    defaults
pillow                    8.1.0            py38he98fc37_0    defaults
pip                       20.3.3           py38h06a4308_0    defaults
python                    3.8.5                h7579374_1    defaults
pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
readline                  8.0                  h7b6447c_0    defaults
setuptools                52.0.0           py38h06a4308_0    defaults
six                       1.15.0           py38h06a4308_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
torchaudio                0.7.2                      py38    pytorch
torchvision               0.8.2                py38_cu102    pytorch
typing_extensions         3.7.4.3                    py_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h9ceee32_0    defaults

Hopefully this will be useful for others.

**Comment by chrischoy** [comment]
The only dependency is 
- pytorch
- numpy
 as specified in the readme and it works for latest versions.
That is why the versions are not specified. No need to install all the other dependencies that won't be used.
