### ISSUE TITLE
Installation error: Unknown option '-fopenmp'

### ISSUE THREAD

**Issue by skanti** [NVIDIA/MinkowskiEngine#311]
**Describe the bug**
Hi Chris,
when building from source thru `python setup.py install` I get following error message:

```
nvcc fatal   : Unknown option '-fopenmp'
```
Any idea how come? I tried `gcc8.4.0` and also few lower CUDA version but with the same outcome.

**To Reproduce**
python setup.py install

**Expected behavior**

'-fopenmp' should be known

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04
 - Python version: 1.8.0 (nightly)
 - CUDA version: 11.2
 - NVIDIA Driver version:  460.32.03
 - Minkowski Engine version 0.5.0
 - GCC version: 9.3.0

**Comment by chrischoy** [comment]
Hi Armen,

Could you try pytorch 1.7?
I'm using the default pytorch c extension for compilation and do not provide `-fopenmp` for nvcc compilation arguments.
It seems that pytorch 1.8 is adding the `-fopenmp` without `-Xcompiler`, which is possibly the reason why you are getting this error.

**Comment by skanti** [comment]
The error can be fixed when passing `-Xcompiler -fopenmp` to nvcc in `setup.py`. Perhaps newer pytorch versions omit `-Xcompiler`

**Comment by plusk01** [comment]
use `ninja` - see https://github.com/NVIDIA/MinkowskiEngine/issues/208

**Comment by eusansone-dev** [comment]
Thank you so much!!  Adding  -Xcompiler -fopenmp to nvcc, that really works!!

**Comment by justStarG** [comment]
> Thank you so much!! Adding -Xcompiler -fopenmp to nvcc, that really works!!

Where should I add this line?

**Comment by Xavier-wa** [comment]
Could you show me how to add it plz

> 在 中传递给 nvcc 时可以修复该错误。也许较新的 pytorch 版本省略了`-Xcompiler -fopenmp``setup.py``-Xcompiler`

**Comment by Xavier-wa** [comment]
> Thank you so much!! Adding -Xcompiler -fopenmp to nvcc, that really works!!

Could you show me how to add it plz @eusansone-dev

**Comment by Zimiao1025** [comment]
Update cmake to v3.22.5 available for me

**Comment by chaitanya1chawla** [comment]
To add -Xcompiler to nvcc compilation,
go to setup.py and edit line 160 https://github.com/NVIDIA/MinkowskiEngine/blob/master/setup.py#L176

Edit it to - 
`    CC_FLAGS += ["-fopenmp", "-Xcompiler"]`
