### ISSUE TITLE
Errors in classification example

### ISSUE THREAD

**Issue by ShiQiu0419** [NVIDIA/MinkowskiEngine#318]
Hi Chris,

Thanks for your great contribution in this work, I successfully install and test several examples.
However, when I run the classification example, I met the following error in ``resnet.py`` :

**Describe the bug**
![image](https://user-images.githubusercontent.com/17152074/108677377-b11f3780-753d-11eb-927f-14944a5d7736.png)

**To Reproduce**
``python -m examples.modelnet40``

**Expected behavior**
I suppose the error is caused by a misalignment in the ``dimension[0]`` of ``otensor`` and ``x`` at : https://github.com/NVIDIA/MinkowskiEngine/blob/ae6db31203ba012df2f695576e2d3819d49bf2d7/examples/resnet.py#L210

To solve it, I tried to quantize``x`` by running something like ``x.sparse()``, however, it seems the function ``cat_slice()`` calls ``invert_mapping()``:
https://github.com/NVIDIA/MinkowskiEngine/blob/ae6db31203ba012df2f695576e2d3819d49bf2d7/MinkowskiEngine/MinkowskiSparseTensor.py#L630   while ``invert_mapping()`` only supports the TensorField type.

I am new to MinkEngine, and still learning it. Would you please help me fix it?

**Desktop (please complete the following information):**

 - OS: Ubuntu 16.04
 - Python version: 3.6
 - CUDA version: 10.2
 - NVIDIA Driver version: 440.64
 - Minkowski Engine version 0.5.1

**Comment by chrischoy** [comment]
Thanks for reporting the issue. The example has been updated on https://github.com/NVIDIA/MinkowskiEngine/commit/258433ebb0c30056e468ee7b7df4576559a5396c.
