### ISSUE TITLE
Does 'sparse_quantize' function support label-collision?

### ISSUE THREAD

**Issue by chrockey** [NVIDIA/MinkowskiEngine#322]
**Describe the bug**
I'm not sure it is intended that 'sparse_quantize' function does not support label collision now.
https://github.com/NVIDIA/MinkowskiEngine/blob/7c3b87ffaf2fa4c5ee452b513b0f781d988d1bfa/MinkowskiEngine/utils/quantization.py#L269

**To Reproduce**
Use sparse_quantize function with label collision.

**Expected behavior**
Return ignore_label when there is label collision in a voxel.

**Comment by chrischoy** [comment]
Yes, the sparse quantize now do not support label collision in v0.5

From v0.5, I recommend not quantizing the point cloud during the data loading and use `.slice()` on a sparse tensor to recover the original point cloud like the example https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/indoor.py#L152.
