### ISSUE TITLE
MinkowskiEngine Upsample

### ISSUE THREAD

**Issue by vhewes** [NVIDIA/MinkowskiEngine#325]
Would it be possible to implement a basic version of PyTorch's Upsample module, which upsamples the image without performing a convolution? I'm adapting a dense model, and MinkowskiEngine has no clear analogue for this module. This procedure is fundamentally different for a sparse pixel map than a dense one, but once could imagine a module which performs the same coordinate transformation as MinowskiConvolutionTranspose, but simply passes the features from input pixels to output pixels without convolving them.

**Comment by victoryc** [comment]
I also ran into a need for something like this. Specifically, what I need is the analog of torch.nn.functional.interpolate with mode='nearest' for upsampling.

**Comment by chrischoy** [comment]
For the linear interpolation to upsample features, please refer to the https://nvidia.github.io/MinkowskiEngine/source/MinkowskiEngine.html?highlight=interpolation#module-MinkowskiEngine.MinkowskiInterpolation
