### ISSUE TITLE
TypeError: only integer tensors of a single element can be converted to an index

### ISSUE THREAD

**Issue by AgnieszkaZaba** [NVIDIA/MinkowskiEngine#327]
Hi,
I'm starting with MinkowskiEngine and I have a problem with preparing data as SparseTensor. I have a model based on Minkowski Convolution Network. I want to make prediction on my own data. 
I use:
torch=1.7.0
MinkowskiEngine=0.4.3 (cant use 0.5.0 due to my model configuration).

```
data = mydata
coords = torch.cat([data.origin_id.int().reshape((-1,1)), data.pos.int()], -1)
sinput = ME.SparseTensor(data.rgb, coords=coords).to(device)
```

sinput is like this:
```
SparseTensor(
  Coords=tensor([[     0,      0,      1,      0],
        [     1,      0,      1,      0],
        [     2,      0,      1,      0],
        ...,
        [134357,      6,      1,      1],
        [134358,      6,      1,      1],
        [134359,      6,      1,      1]], dtype=torch.int32)
  Feats=tensor([[0.3608, 0.2980, 0.2157],
        [0.2510, 0.2039, 0.1529],
        [0.3216, 0.2588, 0.2039],
        ...,
        [0.3922, 0.3529, 0.3333],
        [0.4431, 0.4157, 0.3843],
        [0.5059, 0.4745, 0.4353]], device='cuda:0')
  coords_key=< CoordsKey, key: 15034981587763204738, tensor_stride: [1, 1, 1, ] in dimension: 3 >
  tensor_stride=[1, 1, 1]
  coords_man=< CoordsManager
	Number of Coordinate Maps: 1 
		Coordinate Map Key: 15034981587763204738, Size: 134360
	Number of Kernel Maps: 0 >
  spatial dimension=3)
```

When I try to put this in my model:

```
model2(sinput)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-136-055282e01386> in <module>
----> 1 model2(sinput)

~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/torch-points3d/torch_points3d/modules/MinkowskiEngine/res16unet.py in forward(self, x)
    456         out = self.bn1(out)
    457         out = self.relu(out)
--> 458         out_b1p2 = self.block1(out)
    459 
    460         out = self.conv2p2s2(out_b1p2)

~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/.local/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
    115     def forward(self, input):
    116         for module in self:
--> 117             input = module(input)
    118         return input
    119 

~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/torch-points3d/torch_points3d/modules/MinkowskiEngine/res16unet.py in forward(self, x)
     37         residual = x
     38 
---> 39         out = self.conv1(x)
     40         out = self.norm1(out)
     41         out = self.relu(out)

~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/envs/points3d/lib/python3.8/site-packages/MinkowskiEngine/MinkowskiConvolution.py in forward(self, input, coords)
    261         # Create a region_offset
    262         self.region_type_, self.region_offset_, _ = \
--> 263             self.kernel_generator.get_kernel(input.tensor_stride, self.is_transpose)
    264 
    265         if self.use_mm and coords is None:

~/anaconda3/envs/points3d/lib/python3.8/site-packages/MinkowskiEngine/Common.py in get_kernel(self, tensor_stride, is_transpose)
    345                 if is_transpose else torch.Tensor([1, ] * self.dimension)
    346 
--> 347             self.cache[tuple(tensor_stride)] = convert_region_type(
    348                 self.region_type, tensor_stride, self.kernel_size, up_stride,
    349                 self.dilation, self.region_offsets, self.axis_types,

~/anaconda3/envs/points3d/lib/python3.8/site-packages/MinkowskiEngine/Common.py in convert_region_type(region_type, tensor_stride, kernel_size, up_stride, dilation, region_offset, axis_types, dimension, center)
    270         # Convert to CUSTOM type
    271         region_type = RegionType.CUSTOM
--> 272         region_offset = torch.IntTensor(region_offset)
    273         kernel_volume = int(region_offset.size(0))
    274 

TypeError: only integer tensors of a single element can be converted to an index
```

Is there a simple way to fix this without updating MinkowskiEngine to 0.5.0?
I don't know why tensor_stride in coords_key is [1, 1, 1, ]. Maybe it is a problem.

**Comment by Gofinge** [comment]
Same problem

**Comment by chrischoy** [comment]
Unfortunately, v0.4.3 won't be supported anymore.

**Comment by Randl** [comment]
Using `region_offset = torch.tensor(region_offset).int()` instead fixes the problem.

**Comment by AgnieszkaZaba** [comment]
> Using `region_offset = torch.tensor(region_offset).int()` instead fixes the problem.

Unfortunately doesn't work for me.


~/anaconda3/envs/points3d/lib/python3.8/site-packages/MinkowskiEngine/Common.py in convert_region_type(region_type, tensor_stride, kernel_size, up_stride, dilation, region_offset, axis_types, dimension, center)
    270         # Convert to CUSTOM type
    271         region_type = RegionType.CUSTOM
--> 272 
    273         region_offset = torch.tensor(region_offset).int()
    274         kernel_volume = int(region_offset.size(0))

TypeError: only integer tensors of a single element can be converted to an index

**Comment by AgnieszkaZaba** [comment]
> Using `region_offset = torch.tensor(region_offset).int()` instead fixes the problem.

Thanks, I changed it and restarted kernel. It works now. Thank you for help.

**Comment by maryamdarei** [comment]
resize_to = transforms.Resize((227, 227))
model.eval()
directory = '/content/drive/MyDrive/Herbarium Data-2019/Data/sample/val'


files = os.listdir(directory)
for filename in files:
  img_files = os.listdir('/content/drive/MyDrive/Herbarium Data-2019/Data/sample/val/'+filename)
  for img_file in img_files:
    input_image = Image.open('/content/drive/MyDrive/Herbarium Data-2019/Data/sample/val/'+filename+"/"+img_file)
    preprocess = transforms.Compose(
          [
              resize_to,
              transforms.ToTensor(),
              transforms.Normalize(
                  mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
              ),  # IMPORTANT: normalize for pretrained models
          ]
    )
    input_tensor = preprocess(input_image)
    input_batch = input_tensor.unsqueeze(0)  # create a mini-batch as expected by the model

    # move the input and model to GPU for speed if available
    if torch.cuda.is_available():
      input_batch = input_batch.to("cuda")
      model.to("cuda")

    with torch.no_grad():
        output = model(input_batch)

    # The output has unnormalized scores. To get probabilities, you can run a softmax on it.
    probabilities = torch.nn.functional.softmax(output[0], dim=0)
    x , y = torch.topk(probabilities, 10) 
    print("real class name: ", foldername_to_class[str(filename)])
    print(f"image {img_file} Detecting for class {categories[y]} by model {modelname}")
    print("--------------------------------")
    # Show top categories per image
    top5_prob, top5_catid = torch.topk(probabilities, 10)
    #top1_prob, top1_catid = torch.topk(probabilities, )
    #print(categories[top1_catid[i]])
    for i in range(top5_prob.size(0)):
        print(categories[top5_catid[i]], top5_prob[i].item())
    print("--------------------------------")

    if categories[y] != foldername_to_class[filename]:
      
      targets = [ClassifierOutputTarget(6)] #0 for finch ?

      grayscale_cam = cam(input_batch, targets=None,aug_smooth=True)

      grayscale_cam = grayscale_cam[0, :]


      img=np.array(input_image.resize(resize_size),np.float32)
      img = img.reshape(img.shape[1],img.shape[0],img.shape[2])
      img = img/255
      visualization = show_cam_on_image(img, grayscale_cam, use_rgb=True)
      visualization = Image.fromarray(visualization)
      fig, ax = plt.subplots(1, 2)
      ax[0].imshow(visualization, cmap='gray')
      ax[1].imshow(input_image.resize(resize_size), cmap='gray')



And I received below error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-86-8b1f44195f70>](https://localhost:8080/#) in <module>
     42     #print(categories[y])
     43     print("real class name: ", foldername_to_class[str(filename)])
---> 44     print(f"image {img_file} Detecting for class {categories[y]} by model {modelname}")
     45     #print(f"Detecting for class {img_file + foldername_to_class[str(filename)} +  model {modelname}")
     46     print("--------------------------------")

TypeError: only integer tensors of a single element can be converted to an index
