### ISSUE TITLE
Minkowski Convolution  and Keras Convolution

### ISSUE THREAD

**Issue by gjain7** [NVIDIA/MinkowskiEngine#334]
Hello , I am really interested in knowing more about Minkowski Engine.
I am kind off new to this concept.

Can we combine keras along with MinkowskiEngine library.

I needed to do 3D MinkowskiConvolution. Along with that I  also intended to add 3D keras convolution within another function.
So, is it feasible to use both these libraries in a single project work.

**Comment by chrischoy** [comment]
keras is simply a wrapper around ml frameworks.
A similar but specialized framework is pytorch lightning for which I provide a basic training example on https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/multigpu_lightning.py

You can extract the network architecture you built on keras to pytorch and then combine with MinkowskiEngine.

**Comment by gjain7** [comment]
Thank You very much for replying so fast . It was really helpful.
