### ISSUE TITLE
slice(X)  in pytorch1.8.1

### ISSUE THREAD

**Issue by Jhcnsn** [NVIDIA/MinkowskiEngine#343]
**Describe the bug**

run classification_modelnet40.py with minkfcnn

/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [56,0,0], thread: [52,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [56,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [56,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [56,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [56,0,0], thread: [29,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

Traceback (most recent call last):
  File "/home/111/MinkowskiEngine/examples/classification_modelnet40.py", line 297, in <module>
    mytrain(net, device, config)
  File "/home/111/MinkowskiEngine/examples/classification_modelnet40.py", line 269, in mytrain
    logit = net(input)
  File "/media/111/DA18EBFA09C1B27D/anaconda3/envs/mink102/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/111/MinkowskiEngine/examples/classification_modelnet40.py", line 148, in forward
    x3 = y3.slice(x)
  File "/home/111/MinkowskiEngine/MinkowskiEngine/MinkowskiSparseTensor.py", line 565, in slice
    self.F[X.inverse_mapping(self.coordinate_map_key).long()],
  File "/home/111/MinkowskiEngine/MinkowskiEngine/MinkowskiTensorField.py", line 351, in inverse_mapping
    _, stride_map = self.coordinate_manager.stride_map(
  File "/home/111/MinkowskiEngine/MinkowskiEngine/MinkowskiCoordinateManager.py", line 430, in stride_map
    return self._manager.stride_map(in_key, stride_key)
RuntimeError:  device-side assert triggered at /home/111/MinkowskiEngine/src/storage.cuh:92

**Desktop (please complete the following information):**

==========System==========
Linux-5.4.0-70-generic-x86_64-with-glibc2.10
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
3.8.8 (default, Feb 24 2021, 21:46:12) 
[GCC 7.3.0]
==========Pytorch==========
1.8.1+cu102
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 460.56
CUDA Version 11.2
VBIOS Version 90.16.4F.00.02
Image Version G001.0000.02.04
==========NVCC==========
/usr/local/cuda-10.2/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
==========CC==========
/usr/bin/c++
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.2
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 10020
CUDART version MinkowskiEngine is compiled: 10020

**Comment by Larry-u** [comment]
Same problem with pytorch 1.7.1+cu102 CUDA 10.2

**Comment by chrischoy** [comment]
Thanks for reporting the issue. Please reinstall from the latest master.

**Comment by volcanoh** [comment]
same issue with latest master branch.

**Comment by chrischoy** [comment]
@volcanoh can you please make a new issue with a minimal reproducible code? Thanks
