### ISSUE TITLE
vae experiments

### ISSUE THREAD

**Issue by christinazavou** [NVIDIA/MinkowskiEngine#344]
Hello and many thanks for the open source code.

After looking at your example of vae.py, I was wondering whether more models have been reported, e.g. training a vae/ae on multiple shapes of the partnet dataset together, and how much time was needed, and under what hyperparameter configurations. Any pointing to related work would be helpful!

Thanks in advance

**Comment by chrischoy** [comment]
Currently, I haven't trained a model with different categories, but you can give it a shot. I don't recall the training time and would vary depending on your GPU setup so you can just run the script first to get a sense of how long this would take on your setup.

Also, the GenerativeConvolutionTranspose is discussed in 

```
@inproceedings{gwak2020gsdn,
  title={Generative Sparse Detection Networks for 3D Single-shot Object Detection},
  author={Gwak, JunYoung and Choy, Christopher B and Savarese, Silvio},
  booktitle={European conference on computer vision},
  year={2020}
}
```

but the VAE part is simply based on 2D VAE examples.

**Comment by christinazavou** [comment]
Ok, thank you for your reply.

Regarding this reconstruction I have another question.
I wanted to use **Chamfer Distance** as a loss function **instead of the Binary Cross Entropy**.

I have some code for chamfer distance, which accepts a source point cloud batch and a target point cloud batch and works well with other (non minkowski based) network implementations, and I tried to plug it in here.

In your vae.py example I just replaced the loss calculation part with the following:

```
      self.reconstruction_coef = 0.002
      self.chamfer_loss =CustomChamferDistance()
      .
      .
      .
      batch_coords_out, _ = sout.decomposed_coordinates_and_features
      batch_coords_in, _ = sin.decomposed_coordinates_and_features

      num_layers, chamf_loss = len(out_cls), 0.
      for coords_pred, coords_orig in zip(batch_coords_out, batch_coords_in):
          assert len(batch_coords_out) > 0
          curr_loss = self.chamfer_loss(coords_orig.unsqueeze(0).float(),
                                        coords_pred.unsqueeze(0).float())
          chamf_loss += self.reconstruction_coef*curr_loss / num_layers

      KLD = -0.5 * torch.mean(torch.mean(1 + log_vars.F - means.F.pow(2) - log_vars.F.exp(), 1))
      loss = KLD + chamf_loss
```

This seems to run without any exceptions ...
However, if I switch to an autoencoder, by replacing 
```
        out = self.global_pool(out)
        mean = self.linear_mean(out)
        log_var = self.linear_log_var(out)
        return mean, log_var
```
with 
```
        out = self.global_pool(out)
        return out
```
in the Encoder's forward() function and replacing
```
        means, log_vars = self.encoder(sinput)
        zs = means
        if self.training:
            zs = zs + torch.exp(0.5 * log_vars.F) * torch.randn_like(log_vars.F)
        out_cls, targets, sout = self.decoder(zs, gt_target)
```
with 
```
        zs = self.encoder(sinput)
        out_cls, targets, sout = self.decoder(zs, gt_target)
```
in the model's forward function().

**the same loss calculation is now give me the error** 
```RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn```

My guess is that the gradients can't get through the operation

```
      batch_coords_out, _ = sout.decomposed_coordinates_and_features
      batch_coords_in, _ = sin.decomposed_coordinates_and_features
```

but then why is there no such error in Vae? Do you have any hint on this?

Thanks in advance
