### ISSUE TITLE
Question about MinkowskiEngine.utils.coords.get_coords_map(x, y)

### ISSUE THREAD

**Issue by yichen928** [NVIDIA/MinkowskiEngine#348]
Hello, thank you for this work! 

I noticed that you have removed the function `get_coords_map()` in `utils/__init__.py`, which is different from your document. And how could I get the mapping between two SparseTensors with different strides (i.e. [1, 1, 1] and [2,2,2]/[4,4,4] ) in this case?

I have tried to re-add this function `get_coords_map()` in `utils/__init__.py`. However, I got an error as follows:
`AttributeError: 'SparseTensor' object has no attribute 'coords_man' `
so I still failed to use it.

Can you tell me how to get the mapping between SparseTensors with your new version of codes? Thank you very much!

**Comment by chrischoy** [comment]
The function has been renamed to [`stride_map`](https://nvidia.github.io/MinkowskiEngine/coords.html?highlight=stride_map#MinkowskiEngine.CoordinateManager.stride_map).

**Comment by HaFred** [comment]
Hi @chrischoy Chris, I am using v0.5.4 and I ran into the same error as above when issuing `get_coords_map(sparse_tensor_a, sparse_tensor_b)`. Would you please let us know which one is the right API to use? Since `get_coords_map()` remains in the current version. Thank you!

**Comment by Quyans** [comment]
> 

hi there, I met the same error amd using v0.5.4.  I met excatly  the same error as yours, have you solve the problem?

**Comment by VasilikiVas** [comment]
@HaFred @Quyans Did you find any solution?
@yichen928 Did stride_map work for you? If yes, how?

**Comment by Quyans** [comment]
已收到邮件

**Comment by VasilikiVas** [comment]
What does it mean?

**Comment by yhyang-myron** [comment]
@Quyans @HaFred @VasilikiVas @yichen928 @chrischoy 
Hi, have you solved this problem? And how to use stride_map? :)

**Comment by Quyans** [comment]
已收到邮件

**Comment by Quyans** [comment]
@yhyang-myron @VasilikiVas  sorry for response too late, yes I solve this,  
you just need to change MinkowskiEngine/utils/coords.py from

assert isinstance(x, SparseTensor)
    assert isinstance(y, SparseTensor)
    assert (
        x.coords_man == y.coords_man
    ), "X and Y are using different CoordinateManagers. Y must be derived from X through strided conv/pool/etc."
    return x.coords_man.get_coords_map(x.coords_key, y.coords_key)


to
assert isinstance(x, SparseTensor)
    assert isinstance(y, SparseTensor)
    assert (
        x.coordinate_manager == y.coordinate_manager
    ), "X and Y are using different CoordinateManagers. Y must be derived from X through strided conv/pool/etc."
    return x.coordinate_manager.stride_map(x.coordinate_map_key, y.coordinate_map_key)

**Comment by Quyans** [comment]
assert isinstance(x, SparseTensor)
    assert isinstance(y, SparseTensor)
    assert (
        x.coords_man == y.coords_man
    ), "X and Y are using different CoordinateManagers. Y must be derived from X through strided conv/pool/etc."
    return x.coords_man.get_coords_map(x.coords_key, y.coords_key)

**Comment by yhyang-myron** [comment]
Thank you !

**Comment by Quyans** [comment]
已收到邮件
