### ISSUE TITLE
Question about the completion task.

### ISSUE THREAD

**Issue by Lillian9707** [NVIDIA/MinkowskiEngine#360]
Hi, thanks for the incredible framework for point cloud processing.
However, when I read your code on the completion task in [examples/completion.py,](https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/completion.py) I noticed that the input of the network is still the complete point cloud:

In line 541, 
`sin = ME.SparseTensor(
            features=in_feat,
            coordinates=data_dict["coords"],
            device=device,        )`
where data_dict['coords'] refers to point cloud which is not randomly cropped.

I wonder if I have misunderstood the code.

**Comment by chrischoy** [comment]
Please refer to the transformation class in the same file. It is the cropped data.
