### ISSUE TITLE
Problem in loading the pre-trained model : inconsistent testing results

### ISSUE THREAD

**Issue by muberrayener** [NVIDIA/MinkowskiEngine#362]
I have a trouble when using pretrained model. I saved model's state_dict after training, then i loaded it, applied it on test data. It gave inconsistent results because i used the same data for visualizing test loss during training.

I use ubuntu 20.04, and latest ME version, Python3.8

==========System==========
Linux-5.8.0-50-generic-x86_64-with-glibc2.10
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]
==========Pytorch==========
1.7.1
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
==========NVCC==========
sh: 1: nvcc: not found
==========CC==========
/usr/bin/c++
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.2
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 11010
CUDART version MinkowskiEngine is compiled: 11010

**Comment by chrischoy** [comment]
It seems like the indoor.py example in the MinkowskiEngine example folder is working fine. Are you sure it is the library not your code thats causing the issue?

**Comment by muberrayener** [comment]
If I try to save the whole model using torch.save(model, file_name), it gives the error below:
TypeError: cannot pickle 'MinkowskiConvolutionFunction' object

**Comment by chrischoy** [comment]
I'm pretty sure the error is in your code. Please try to use just regular pytorch dense 3D convnets first to figure out which part is causing the error.

**Comment by muberrayener** [comment]
Thank you for your advice, i will try it.

**Comment by vgthengane** [comment]
@muberrayener How did you solve the error?

**Comment by muberrayener** [comment]
> @muberrayener How did you solve the error?

I tried to solve but nothing worked. I changed the network from MinkowskiFCNN to Minkowski ResNet, the problem disappeared.
