### ISSUE TITLE
Incorrect Results with MinkowskiInterpolation

### ISSUE THREAD

**Issue by CSautier** [NVIDIA/MinkowskiEngine#363]
**Describe the bug**

Linear interpolation provided with MinkowskiInterpolation gives incoherent and incorrect results.

************************************************************************************
**To Reproduce**

```
import torch
import MinkowskiEngine as ME
pc = torch.tensor([[0., 1.], [1., 0.]])
features = torch.tensor([[0.], [1.]])
C, F = ME.utils.sparse_quantize(pc, features)
sparse_tensor = ME.SparseTensor(F, C)
interp = ME.MinkowskiInterpolation()

interpolate_pc = torch.tensor([[0.6, 0.6]])
print(interp(sparse_tensor , interpolate_pc))
> tensor([[0.4000]])

interpolate_pc = torch.tensor([[0., 0.]])
print(interp(sparse_tensor , interpolate_pc))
> tensor([[0.]])
```

************************************************************************************
**Expected behavior**

```
import torch
import MinkowskiEngine as ME
pc = torch.tensor([[0., 1.], [1., 0.]])
features = torch.tensor([[0.], [1.]])
C, F = ME.utils.sparse_quantize(pc, features)
sparse_tensor = ME.SparseTensor(F, C)
interp = ME.MinkowskiInterpolation()

interpolate_pc = torch.tensor([[0.6, 0.6]])
print(interp(sparse_tensor , interpolate_pc))
> tensor([[0.5000]])

interpolate_pc = torch.tensor([[0., 0.]])
print(interp(sparse_tensor , interpolate_pc))
> tensor([[0.5000]])
```

************************************************************************************
**Desktop:**

 - OS: Ubuntu 18.04 (Docker)
 - Python version: 3.7.10
 - Pytorch version: 1.8.1
 - CUDA version: 10.2
 - NVIDIA Driver version: 460.67
 - Minkowski Engine version 0.5.4

**Comment by chrischoy** [comment]
It is giving you the accurate result.

[0, 1]  --> batch 0 coordinate 1
[1, 0] --> batch 1 coordinate 0

[0.6, 0.6] is actually an invalid query since batch 0.6 doesn't exist. It will use the nearest integer which is 1 for batch index.

For [0, 0], it is quering coordinate 0 at batch 0.
