### ISSUE TITLE
install freeze on building wheels for existing packages 

### ISSUE THREAD

**Issue by trinhnhut-gif** [NVIDIA/MinkowskiEngine#364]
!pip install pyvistaqt
!sudo apt-get install build-essential python3-dev libopenblas-dev -y
!pip install -U git+https://github.com/NVIDIA/MinkowskiEngine --no-deps

![1](https://user-images.githubusercontent.com/85855232/122643090-5b9c1580-d140-11eb-99b1-7dfdc870ecd2.jpg)
then the install freeze on building wheels for MinkowskiEngine

**Desktop:

 - OS: Ubuntu 20.04
 - Python version: 3.8
 - Pytorch version: 1.9.0
 - CUDA version: 11.2
 - NVIDIA Driver version: 465.89
 - Minkowski Engine version 0.5.4

```

**Comment by chrischoy** [comment]
Could you try setting the max jobs?

**Comment by trinhnhut-gif** [comment]
HI Chrischoy. Its worked perfectly. Thank you so much.
