### ISSUE TITLE
Voxelization of input

### ISSUE THREAD

**Issue by shreyakatari** [NVIDIA/MinkowskiEngine#375]
Hi @chrischoy  Can we give voxelized input to training instead of original  input? Will it affect the performance of training as their is prevoxel transform as well in semantic segmentation.
Thank you.

**Comment by chrischoy** [comment]
You can give either the original or prevoxelized input. If you have more sophisticated network with interpolation, there could be some performance gain but not too much different if the voxel size is really small.
