### ISSUE TITLE
Upsampling features in sparse voxels to point-level features or point cloud features

### ISSUE THREAD

**Issue by pvnieo** [NVIDIA/MinkowskiEngine#378]
Hi,

Thanks for the amazing library.

My use case is that I'm using res-unet type of architecture, on moderately small point clouds, and I want to compute features using my architecture for all the pointclouds, without using a very small voxel_size, how can I do that?

For example, let's suppose my point cloud has 6000 points, and after voxelization it become 5200 points, but I want is to have features for all the 6000 points!

Thank you in advance!

**Comment by chrischoy** [comment]
There are two ways to convert voxel-wise features to point-wise features 

1. Copy a voxel feature to all points that belong to the same voxel
2. Use trilinear interpolation to extract features for all points

 Minkowski Engine supports both methods.

1. Use `slice` function. This copies a voxel feature to all points inside the voxel. See https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/indoor.py#L152
2. Use `interpolate` function. This uses N-dimensional interpolation. See https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/classification_modelnet40.py#L260

**Comment by pvnieo** [comment]
Hi @chrischoy 

This answer my question!

Closing the issue, but will open it if I need further information!
