### ISSUE TITLE
assertion in MinkowskiToSparseTensor 

### ISSUE THREAD

**Issue by yushiangw** [NVIDIA/MinkowskiEngine#387]
**Describe the bug**

The current assertion in MinkowskiToSparseTensor actually forbids coordinates input.
https://github.com/NVIDIA/MinkowskiEngine/blob/9f81ae66b33b883cd08ee4f64d08cf633608b118/MinkowskiEngine/MinkowskiOps.py#L391

probably the correct one
```` remove_zeros == coordinates is None ```` 

************************************************************************************
**To Reproduce**

````
dense_tensor = torch.rand(3, 4, 11, 11, 11, 11)  # BxCxD1xD2x....xDN
dense_tensor.requires_grad = True

# Since the shape is fixed, cache the coordinates for faster inference
coordinates = dense_coordinates(dense_tensor.shape)

MinkowskiToSparseTensor(coordinates=coordinates)

````

**Comment by chrischoy** [comment]
The documentation clearly states that you have to provide `remove_zeros=False` to use the coordinates.
However, since it can be inferred that the coordinates have precedence over the remove_zeros, I'll update the behavior to require only the coordinates without remove_zeros.
