### ISSUE TITLE
g++:erroe

### ISSUE THREAD

**Issue by DroseGao** [NVIDIA/MinkowskiEngine#393]
CUDA:11.1
ubuntu:16.04
python:3.8
torch;1.9.0
I use setup.py then it tells:
`WARNING: Skipping MinkowskiEngine as it is not installed.
--------------------------------
| CUDA compilation set         |
--------------------------------

Using BLAS=openblas
Using the default compiler
running install
running bdist_egg
running egg_info
writing MinkowskiEngine.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngine.egg-info/dependency_links.txt
writing requirements to MinkowskiEngine.egg-info/requires.txt
writing top-level names to MinkowskiEngine.egg-info/top_level.txt
reading manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiChannelwiseConvolution.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/diagnostics.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiSparseTensor.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiTensorField.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/sparse_matrix_functions.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiTensor.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCommon.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCoordinateManager.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiKernelGenerator.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiInterpolation.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine
creating build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/summary.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/utils
creating build/lib.linux-x86_64-3.8/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-3.8/MinkowskiEngine/modules
running build_ext
building 'MinkowskiEngineBackend._C' extension
creating /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8
creating /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home
creating /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq
creating /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine
creating /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src
creating /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/pybind
Emitting ninja build file /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
creating build/lib.linux-x86_64-3.8/MinkowskiEngineBackend
g++ -pthread -shared -B /home/gpq/anaconda3/compiler_compat -L/home/gpq/anaconda3/lib -Wl,-rpath=/home/gpq/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/math_functions_cpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/math_functions_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/coordinate_map_manager.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/coordinate_map_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_transpose_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pooling_avg_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pooling_max_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/local_pooling_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/local_pooling_transpose_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/global_pooling_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/broadcast_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/broadcast_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pruning_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/interpolation_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/spmm.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/quantization.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/direct_max_pool.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/pybind/minkowski.o -L/home/gpq/anaconda3/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-11.1/lib64 -lcusparse -lopenblas -lopenblas -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.8/MinkowskiEngineBackend/_C.cpython-38-x86_64-linux-gnu.so
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/math_functions_cpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/math_functions_gpu.o:No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/coordinate_map_manager.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/coordinate_map_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_kernel.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_gpu.o:No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_transpose_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pooling_avg_kernel.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pooling_max_kernel.o:No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/local_pooling_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/local_pooling_transpose_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/global_pooling_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/broadcast_kernel.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/broadcast_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pruning_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/interpolation_gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/spmm.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/gpu.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/quantization.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/direct_max_pool.o: No such file or directory
g++: error: /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/pybind/minkowski.o: No such file or directory
error: Command "g++ -pthread -shared -B /home/gpq/anaconda3/compiler_compat -L/home/gpq/anaconda3/lib -Wl,-rpath=/home/gpq/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/math_functions_cpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/math_functions_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/coordinate_map_manager.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/coordinate_map_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/convolution_transpose_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pooling_avg_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pooling_max_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/local_pooling_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/local_pooling_transpose_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/global_pooling_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/broadcast_kernel.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/broadcast_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/pruning_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/interpolation_gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/spmm.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/gpu.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/quantization.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/home/gpq/MinkowskiEngine/src/direct_max_pool.o /home/gpq/MinkowskiEngine/build/temp.linux-x86_64-3.8/pybind/minkowski.o -L/home/gpq/anaconda3/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-11.1/lib64 -lcusparse -lopenblas -lopenblas -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.8/MinkowskiEngineBackend/_C.cpython-38-x86_64-linux-gnu.so" failed with exit status 1
`

**Comment by zhangzihui247** [comment]
hello, could you tell me how to solve this issue? I meet same one

**Comment by DroseGao** [comment]
sry I gived up……

**Comment by thiagodma** [comment]
Why is this issue closed? @chrischoy

**Comment by BoPang1996** [comment]
I have the same problem, how to solve this

**Comment by limian1761** [comment]
I checked the  building file, that said .ninja_required_version = 1.3.  My ninjia is 1.10.2.3.  So I reinstall 啊eraly version of ninjia。

for me:  i  use "pip install ninja==1.5.3 ", it works

**Comment by limian1761** [comment]
I checked the  building file, that said .ninja_required_version = 1.3.  My ninjia is 1.10.2.3.  So I reinstall  early version of ninjia。

for me:  i  use "pip install ninja==1.5.3 ", it works

**Comment by thiagodma** [comment]
Guys, try using this dockerfile

```dockerfile
FROM pytorch/pytorch:1.9.1-cuda11.1-cudnn8-devel

WORKDIR /app

##############################################
# You should modify this to match your GPU compute capability
# https://developer.nvidia.com/cuda-gpus#compute
ENV TORCH_CUDA_ARCH_LIST="8.6"
##############################################

ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CUDA_HOME=/usr/local/cuda-11.1
ENV MAX_JOBS=1

# Install dependencies
RUN apt-get update
RUN apt-get install -y git ninja-build cmake build-essential libopenblas-dev \
    xterm xauth openssh-server tmux wget mate-desktop-environment-core

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# activate base conda env
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

RUN pip install -U git+https://github.com/NVIDIA/MinkowskiEngine -v --no-deps --install-option="--force_cuda" --install-option="--blas=openblas"

RUN conda install matplotlib=3.4.2 \
    && conda install pandas=1.3.3 \
    && conda install scikit-learn=0.24.2 \
    && conda install seaborn=0.11.2 \
    && conda install -c open3d-admin open3d

RUN pip install addict plyfile

COPY 3d-fast-slow-motion /app/3d-fast-slow-motion
VOLUME data /app/data
VOLUME scripts /app/scripts

RUN cd 3d-fast-slow-motion && pip install -e .

RUN echo "source activate base" > ~/.bashrc
```

**Comment by wslgqq277g** [comment]
> I checked the building file, that said .ninja_required_version = 1.3. My ninjia is 1.10.2.3. So I reinstall early version of ninjia。
> 
> for me: i use "pip install ninja==1.5.3 ", it works

thanku sir! works for me
