### ISSUE TITLE
Question about MinkowskiEngineBackend

### ISSUE THREAD

**Issue by HOUYONGKUO** [NVIDIA/MinkowskiEngine#444]
Hello! Thank you for your innovative work. But I found the following problem related to MinkowskiEngineBackend when import ME, I can't understand how this problem arises. It seems to be related to the virtual environment of anaconda. Hope to get help.

`ImportError: /home/houyongkuo/.conda/envs/KSConvNet/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngineBackend/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv
`

Thanks

**Comment by HOUYONGKUO** [comment]
I was using pytorch 1.10.2 before, when I switched to 1.9 or 1.10.0 this problem was solved, but another problem appeared:
`ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory`

**Comment by Vikram12301** [comment]
Where is the file MinkowskiEngineBackend, as I am getting an error which states :ModuleNotFoundError: No module named 'MinkowskiEngineBackend.C' when I tried cloning the repo!

**Comment by Yuansen-Huang** [comment]
I wonder how you solved the second problem. I met the problem too.
