### ISSUE TITLE
assertion (in_feat.size(1) == kernel.size(1)) failed. Input feature size and kernel size mismatch

### ISSUE THREAD

**Issue by HOUYONGKUO** [NVIDIA/MinkowskiEngine#456]
Hello, I don't know how to determine the value of the input size and kernel size when I input the convolution, I get the following error when I input, I hope to get your help. Thanks.

`assertion (in_feat.size(1) == kernel.size(1)) failed. Input feature size and kernel size mismatch`

**Comment by 123xldan** [comment]
Hello, how did you solve this problem? I also encountered the same situation.
