### ISSUE TITLE
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HaoyiZhu** [NVIDIA/MinkowskiEngine#494]
When I want to `import MinkowskiEngine as ME`, it says that
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haoyi/projects/MinkowskiEngine/MinkowskiEngine/__init__.py", line 53, in <module>     
    from MinkowskiEngineBackend._C import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

I am using PyTorch 1.12. Is this related to PyTorch version? What should I do if I want to use Pytorch>1.10? Does the official version support this?

Thanks!

**Comment by HaoyiZhu** [comment]
I fixed this issue by re-installing openblas.

**Comment by fuxc1996** [comment]
> I fixed this issue by re-installing openblas.

this works for me! Thanks for sharing!
