### ISSUE TITLE
Installation failed!

### ISSUE THREAD

**Issue by haiduo** [NVIDIA/MinkowskiEngine#495]
Who can help me take a look? I would be very grateful. The process is as followsh https://github.com/NVIDIA/MinkowskiEngine/issues/208#issuecomment-1246672195

:)

**Comment by zsc** [comment]
Maybe you've run out of storage space of /tmp (can be checked by looking at result of `df -h` and see if tmps partition has a high occupancy ratio).

**Comment by haiduo** [comment]
>


> Maybe you've run out of storage space of /tmp (can be checked by looking at result of `df -h` and see if tmps partition has a high occupancy ratio).

Thank you for your reply. I took a look. I don't think that's the problem. 
![image](https://user-images.githubusercontent.com/35062202/190403676-b732a4f0-e290-4989-ae2b-0f07ea07b347.png)

**Comment by haiduo** [comment]
Fortunately, after replacing a  graphic card, the installation succeeded. The operation is as follows:
```
configure：
sysytem：ubuntu18.04 
cuda：10.2  
cudnn：7.6.5

commands orders：
conda create -n py3-mink python=3.8
conda activate py3-mink
conda install openblas-devel -c anaconda
pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0
conda install cudatoolkit=10.2
git clone https://github.com/NVIDIA/MinkowskiEngine.git
cd MinkowskiEngine/
export CXX=g++-7
python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas
```
