### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by wu5chengwei** [NVIDIA/MinkowskiEngine#531]
when i import MinkowskiEngine ,the bug appears.

************************************************************************************
`import MinkowskiEngine as ME `

/home/karenmaxx/anaconda3/envs/pytorch/lib/python3.8/site-packages/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/karenmaxx/anaconda3/envs/pytorch/lib/python3.8/site-packages/MinkowskiEngine/__init__.py", line 53, in <module>
    from MinkowskiEngineBackend._C import (
ImportError: /home/karenmaxx/anaconda3/envs/pytorch/lib/python3.8/site-packages/MinkowskiEngineBackend/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor4div_ERKN3c106ScalarE

************************************************************************************
import MinkowskiEngine successfully

************************************************************************************
**Desktop (please complete the following information):**

 - OS: [ubuntu20.04]
 - Python version: [3.8.16]
 - Pytorch version: [1.7.1]
 - CUDA version: [10.1]
 - NVIDIA Driver version: [510.47]
 - Minkowski Engine version [0.5.4]
 - Output of the following command. (If you installed the latest MinkowskiEngine, paste the output of `python -c "import MinkowskiEngine as ME; ME.print_diagnostics()"`. Otherwise, paste the output of the following command.)

```
wget -q https://raw.githubusercontent.com/NVIDIA/MinkowskiEngine/master/MinkowskiEngine/diagnostics.py ; python diagnostics.py
```
I can't use these two methods.Is there any other way?

************************************************************************************
**Additional context**
my cuda is not in /user/local

`whereis cuda`
cuda: /usr/lib/cuda /usr/include/cuda.h

**Comment by wu5chengwei** [comment]
I saw a similar essue , but it didn't work. I did the following check.
I checked out the CUDA versions in nvcc and pytorch.

`nvcc -v`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

`torch.__version__`
'1.7.1+cu101'

Thank you!

**Comment by lightbot21** [comment]
Hi, I also meet this error, how did you solve that finally?
