### ISSUE TITLE
Error when calling MinkowskiPooling

### ISSUE THREAD

**Issue by LinfengUP** [NVIDIA/MinkowskiEngine#565]
**Describe the bug**
When I apply MinkowskiPooling, it returns \<unknown\> error without any extra information.
![6dc7b4d49ff4dc34a7bc0822f002d5e](https://github.com/NVIDIA/MinkowskiEngine/assets/109070850/bc040bfa-cc78-4213-a871-d3fee2953179)

************************************************************************************
**To Reproduce**
```python
model.pooling = MinkowskiAvgPooling(
            kernel_size=2, stride=2, dimension=3)

with torch.no_grad():
    coordinates = ME.SparseTensor(
        features=raw_coordinates,
        coordinate_manager=aux[-1].coordinate_manager,
        coordinate_map_key=aux[-1].coordinate_map_key,
        device=aux[-1].device)
    coords = [coordinates]
    for _ in reversed(range(len(aux) - 1)):
        coords.append(model.pooling(coords[-1]))
    coords.reverse()
```

************************************************************************************
**Expected behavior**

************************************************************************************
**Desktop (please complete the following information):**

 - OS: [e.g. Ubuntu 18.04]
 - Python version: [3.10]
 - Pytorch version: [1.12.1]
 - CUDA version: [11.3]
 - Minkowski Engine version [0.5.4]

**Comment by Jovendish** [comment]
I encountered the same problem. Has the problem  been solved?

**Comment by LinfengUP** [comment]
> I encountered the same problem. Has the problem been solved?

Oh, I realized I did not add CUDA_HOME in environment variables. Just check whether your nvcc -V can work well.
