### ISSUE TITLE
Error when building wheel for MinkowskiEngine

### ISSUE THREAD

**Issue by ZiyangYan** [NVIDIA/MinkowskiEngine#603]
[21/21] /usr/local/cuda-11.6/bin/nvcc  -I/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/torch/include -I/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/torch/include/TH -I/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.6/include -I/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src -I/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/3rdparty -I/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/include -I/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/include/python3.8 -c -c /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/pybind/minkowski.cu -o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/pybind/minkowski.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' --expt-relaxed-constexpr --expt-extended-lambda -O3 -Xcompiler=-fno-gnu-unique -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
creating build/lib.linux-x86_64-cpython-38/MinkowskiEngineBackend
g++ -pthread -B /media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/compiler_compat -L/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/lib -Wl,-rpath=/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/broadcast_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/broadcast_kernel.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/convolution_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/convolution_kernel.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/convolution_transpose_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/coordinate_map_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/coordinate_map_manager.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/direct_max_pool.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/global_pooling_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/interpolation_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/local_pooling_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/local_pooling_transpose_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/math_functions_cpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/math_functions_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/pooling_avg_kernel.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/pooling_max_kernel.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/pruning_gpu.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/quantization.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/src/spmm.o /media/zyan/sandiskSSD/Gaussian_Splatting_methods/dreamgaussian-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-38/pybind/minkowski.o -L/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-11.6/lib64 -lcusparse -lopenblas -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-38/MinkowskiEngineBackend/_C.cpython-38-x86_64-linux-gnu.so
/media/zyan/sandiskSSD/anaconda3/envs/dreamgaussian/compiler_compat/ld: cannot find -lopenblas: No such file or directory
collect2: error: ld returned 1 exit status
error: command '/usr/bin/g++' failed with exit code 1

**Comment by ZiyangYan** [comment]
Desktop (please complete the following information):

OS: Ubuntu 20.04
Python version: 3.10
Pytorch version: 1.13.0
CUDA version: 11.6
Pip version: 23.3.1
Output of the following command.
python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas

**Comment by tianlinliang** [comment]
yes i meet the same problems , did you have any solutions now?

**Comment by JeremyZhao1998** [comment]
I meet the same issue and it takes me a whole night to solve.

First checkout whether you have installed openblas-devel:

``
conda list openblas
``

If not, install it by:

``
conda install openblas-devel -c anaconda -y
``

The lib file of openblas should be in the path like ``xxx/anaconda3/envs/<env_name>/lib``, but this shit program only looks for the lib files in ``xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib``. So, all we have to do is to copy the ``.so`` files into the right path by:

``
cp xxx/anaconda3/envs/<env_name>/lib/libopenblas.so* xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib/.
``

It works for me, good lock to you. @ZiyangYan @tianlinliang

**Comment by ZheningHuang** [comment]
> I meet the same issue and it takes me a whole night to solve.
> 
> First checkout whether you have installed openblas-devel:
> 
> `conda list openblas`
> 
> If not, install it by:
> 
> `conda install openblas-devel -c anaconda -y`
> 
> The lib file of openblas should be in the path like `xxx/anaconda3/envs/<env_name>/lib`, but this shit program only looks for the lib files in `xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib`. So, all we have to do is to copy the `.so` files into the right path by:
> 
> `cp xxx/anaconda3/envs/<env_name>/lib/libopenblas.so* xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib/.`
> 
> It works for me, good lock to you. [@ZiyangYan](https://github.com/ZiyangYan) [@tianlinliang](https://github.com/tianlinliang)

this works for me! Thanks for sharing!

**Comment by ZiyangYan** [comment]
> I meet the same issue and it takes me a whole night to solve.
> 
> First checkout whether you have installed openblas-devel:
> 
> `conda list openblas`
> 
> If not, install it by:
> 
> `conda install openblas-devel -c anaconda -y`
> 
> The lib file of openblas should be in the path like `xxx/anaconda3/envs/<env_name>/lib`, but this shit program only looks for the lib files in `xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib`. So, all we have to do is to copy the `.so` files into the right path by:
> 
> `cp xxx/anaconda3/envs/<env_name>/lib/libopenblas.so* xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib/.`
> 
> It works for me, good lock to you. [@ZiyangYan](https://github.com/ZiyangYan) [@tianlinliang](https://github.com/tianlinliang)

Thanks bro, it works for me

**Comment by parkie0517** [comment]
> I meet the same issue and it takes me a whole night to solve.
> 
> First checkout whether you have installed openblas-devel:
> 
> `conda list openblas`
> 
> If not, install it by:
> 
> `conda install openblas-devel -c anaconda -y`
> 
> The lib file of openblas should be in the path like `xxx/anaconda3/envs/<env_name>/lib`, but this shit program only looks for the lib files in `xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib`. So, all we have to do is to copy the `.so` files into the right path by:
> 
> `cp xxx/anaconda3/envs/<env_name>/lib/libopenblas.so* xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib/.`
> 
> It works for me, good lock to you. [@ZiyangYan](https://github.com/ZiyangYan) [@tianlinliang](https://github.com/tianlinliang)

It worked, thanks a lot mate!

**Comment by yzh92** [comment]
> I meet the same issue and it takes me a whole night to solve.
> 
> First checkout whether you have installed openblas-devel:
> 
> `conda list openblas`
> 
> If not, install it by:
> 
> `conda install openblas-devel -c anaconda -y`
> 
> The lib file of openblas should be in the path like `xxx/anaconda3/envs/<env_name>/lib`, but this shit program only looks for the lib files in `xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib`. So, all we have to do is to copy the `.so` files into the right path by:
> 
> `cp xxx/anaconda3/envs/<env_name>/lib/libopenblas.so* xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib/.`
> 
> It works for me, good lock to you. [@ZiyangYan](https://github.com/ZiyangYan) [@tianlinliang](https://github.com/tianlinliang)

cool bro!!!

**Comment by ikeke6** [comment]
> I meet the same issue and it takes me a whole night to solve.我遇到了同样的问题，花了一整夜才解决。
> 
> First checkout whether you have installed openblas-devel:首先检查你是否安装了openblas-devel：
> 
> `conda list openblas``conda list打开`
> 
> If not, install it by:如果没有，请通过以下方式安装：
> 
> `conda install openblas-devel -c anaconda -y`
> 
> The lib file of openblas should be in the path like `xxx/anaconda3/envs/<env_name>/lib`, but this shit program only looks for the lib files in `xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib`. So, all we have to do is to copy the `.so` files into the right path by:openlib的lib文件应该在像 `xxx/anaconda3/envs/<env_name>/lib` 这样的路径中，但是这个狗屎程序只在 `xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib` 中查找lib文件。所以，我们所要做的就是通过以下方式将`.so`文件复制到正确的路径中：
> 
> `cp xxx/anaconda3/envs/<env_name>/lib/libopenblas.so* xxx/anaconda3/envs/<env_name>/lib/python3.x/site-packages/torch/lib/.`
> 
> It works for me, good lock to you. 对我有用，对你有用。[@ZiyangYan](https://github.com/ZiyangYan) [@tianlinliang](https://github.com/tianlinliang)

Thanks!!!Your solution is genius!you help me!!

**Comment by OwenCaleb** [comment]
you are genius!
