### ISSUE TITLE
MinkowskiEngine Installation Issue: undefined symbol Error

### ISSUE THREAD

**Issue by zhf321** [NVIDIA/MinkowskiEngine#610]
Description: I was able to successfully compile and use the MinkowskiEngine library on an Ubuntu system. Now, I am trying to install it on a CentOS system where nvcc, pytorch, and gcc all meet the required versions. I have tried multiple times, and although the MinkowskiEngine library compiles correctly, when I attempt to import MinkowskiEngine, I encounter the following error:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import MinkowskiEngine
  File "/home/xxx/project/miniconda3/envs/growsp2/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py", line 53, in <module> 
    from MinkowskiEngineBackend._C import (
ImportError: /home/xxx/project/miniconda3/envs/growsp2/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngineBackend/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs

I have not found a solution to this issue in previous reports, so I am asking for assistance. Does MinkowskiEngine support CentOS? Could you please provide any guidance or suggestions on resolving this issue?

**Comment by lightbot21** [comment]
Hi, I also meet this error, how did you solve that finally?
