### ISSUE TITLE
Possible integration

### ISSUE THREAD

**Issue by tchaton** [NVIDIA/MinkowskiEngine#80]
Dear people from Minkowski Engine,

We plan to regroup in one framework all the SOTA models for point cloud analysis and we were wondering if you would be interested to help us integrate Minkowski Engine within the framework.

You can find the repo here: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks

Best,
Thomas Chaton.

**Comment by chrischoy** [comment]
Hi Thomas,

sounds like a really good initiative! How may I help? All semantic segmentation models are located on another repository https://github.com/chrischoy/SpatioTemporalSegmentation

**Comment by tchaton** [comment]
Hey @chrischoy, could share you email adress with me at thomas.chaton.ai@gmail.com. I will add you to our slack where several great researcher have already join 😁 It is where we are planning all development for the projects.

**Comment by chrischoy** [comment]
Closing since it is integrated.
