### ISSUE TITLE
Potential huge speed up 

### ISSUE THREAD

**Issue by tchaton** [NVIDIA/MinkowskiEngine#97]
Dear All,

I don t know if you are aware of this implementation using csr format: https://github.com/owensgroup/merge-spmm
associated to this paper: https://github.com/owensgroup/GraphBLAS/raw/europar/spmm-europar18-preprint.pdf

It has been implemented / extented within torch-sparse: https://github.com/rusty1s/pytorch_sparse
and Matthias Fey (main author of Pytorch Geometric, Pytorch Scatter, Pytorch Sparse, Pytorch Cluster, etc..) reported important speed (up to perform 3x times to cuda) on sparse matrix multiplication.

"Convolution could potentially be fully implemented on gpu" as sparse matrix multiplication using merge-* algorithm. We have a Slack to discuss all of it, as we are currently integrating Minkowski Engine within https://github.com/nicolas-chaulet/deeppointcloud-benchmarks and we are looking at solution to make it better. Would be great if you could contact me, so we can all think on the best ways to go forward.

Best regards,
Thomas Chaton.

**Comment by chrischoy** [comment]
Hi Thomas,

Thanks for the pointers. However, the generalized convolution for sparse tensors does not rely on spare matrix multiplication. Once we extract [kernel maps](https://stanfordvl.github.io/MinkowskiEngine/terminology.html#kernel-map), we do matrix multiplication. Currently, kernel map generation is done on CPU and it is a bit tricky to implement complex data structures on GPU.

**Comment by ecr23xx** [comment]
Maybe you could look at this implementation of sparse tensor convolution: [spconv](https://github.com/traveller59/spconv)? In this implementation, kernel map is generated by GPU thus should be faster than MinkowskiEngine (according to this [issue](https://github.com/StanfordVL/MinkowskiEngine/issues/22)).

**Comment by chrischoy** [comment]
I see. Thanks for the pointer. They used cudpp hash table and we are planning to incorporate other type of gpu hash tables, but we are stuck on other projects. We will get back to this issue soon.

**Comment by tchaton** [comment]
Any progress on adding gpu hash tables within ME ?

**Comment by chrischoy** [comment]
Closing since v0.5 is publicly available.
